import{revenueSha256,revenueStableId}from"../revenue-01/canonical";
import{APPROVED_ACTION_PACKAGE_CONTRACT_SHA256}from"../revenue-01/approved-action";
import{APPROVED_WORKFORCE_HANDOFF_CONTRACT_SHA256,APPROVED_WORKFORCE_RECEIVER_REGISTRY_SHA256}from"../workforce/handoff";
import{APPROVED_CLOSER_CONTRACT_SHA256}from"./contract";
import{CLOSER_PACKET_ASSEMBLER_VERSION,CLOSER_PACKET_CANONICALIZATION,CLOSER_PACKET_SCHEMA,CLOSER_PACKET_VERSION,type CloserPacketInput,type CloserPacketIssue,type ConversationIntelligencePacketV1}from"./types";

export const CLOSER_PACKET_CONTRACT={schemaVersion:CLOSER_PACKET_SCHEMA,version:CLOSER_PACKET_VERSION,canonicalizationVersion:CLOSER_PACKET_CANONICALIZATION,assemblerVersion:CLOSER_PACKET_ASSEMBLER_VERSION,requiredSections:["binding","sourceContracts","growth","sales","crm","revenue","authority","freshness","issues"],readiness:["ready_to_simulate","not_ready"],maximumAuthority:"preview_readiness",closerInvoked:false,messageSent:false,crmMutation:false,providerInvocation:false,persisted:false,scheduling:false,paymentAction:false,externalAction:false}as const;
export const CLOSER_PACKET_CONTRACT_SHA256=revenueSha256(CLOSER_PACKET_CONTRACT);
export const APPROVED_CLOSER_PACKET_CONTRACT_SHA256="0043dfa94c158a5ca9053c911742481e27a0005aa52ba5a71535a0eb04fe96eb"as const;
export class CloserPacketError extends Error{code:string;constructor(code:string,message:string){super(message);this.name="CloserPacketError";this.code=code;}}
const add=(issues:CloserPacketIssue[],code:string,field:string,message:string,classification:CloserPacketIssue["classification"]="missing")=>issues.push({code,field,message,classification});
const present=(value:unknown)=>typeof value==="string"&&value.trim().length>0;
const current=(at:string,effective:string,expires:string|null)=>{const time=Date.parse(at),start=Date.parse(effective),end=expires===null?null:Date.parse(expires);return Number.isFinite(time)&&Number.isFinite(start)&&time>=start&&(end===null||(Number.isFinite(end)&&time<=end));};
export function verifyCloserPacketContractIntegrity(){if(CLOSER_PACKET_CONTRACT_SHA256!==APPROVED_CLOSER_PACKET_CONTRACT_SHA256)throw new CloserPacketError("packet_contract_drift","The CLOSER Conversation Intelligence Packet contract failed its approved integrity check.");}
export function assembleConversationIntelligencePacket(input:CloserPacketInput):ConversationIntelligencePacketV1{
  verifyCloserPacketContractIntegrity();const issues:CloserPacketIssue[]=[],p=input.revenue.approvedPackage,h=input.revenue.routingPreview;
  const expected={growth:"618b895eb97479db83edc668a32bc4db93a222429b27e2a8f6cbadc2bbb7e860",sales:"0428ae67558fb21d288e3588139a8f46d2fdd17cc436b07f7ce1f17f14c265e6",crm:"68129fc2d2d4fdd5646b93879d0b469a71c3ef4c93e84fd0e4aaccc011fa8194",revenue:"972c2d2dbc482fc6252f05ca77bc2ab1a0c5fd74936bd95fbd30637254a1bb33"};
  for(const[name,actual]of Object.entries({growth:input.growthContract.sha256,sales:input.salesContract.sha256,crm:input.crmContract.sha256,revenue:input.revenueContract.sha256}))if(actual!==expected[name as keyof typeof expected])add(issues,"source_contract_drift",`sourceContracts.${name}`,`${name.toUpperCase()} source contract identity is invalid.`,"invalid");
  if(input.closerContract.sha256!==APPROVED_CLOSER_CONTRACT_SHA256)add(issues,"closer_contract_drift","sourceContracts.closer","Frozen CLOSER contract identity is invalid.","invalid");
  if(p.schemaContractSha256!==APPROVED_ACTION_PACKAGE_CONTRACT_SHA256)add(issues,"approved_package_contract_mismatch","revenue.approvedPackage","Approved Action Package contract identity is invalid.","invalid");
  if(h.handoffContractSha256!==APPROVED_WORKFORCE_HANDOFF_CONTRACT_SHA256||h.receiverRegistrySha256!==APPROVED_WORKFORCE_RECEIVER_REGISTRY_SHA256)add(issues,"handoff_contract_mismatch","revenue.routingPreview","Workforce handoff identities are invalid.","invalid");
  if(p.binding.accountId!==input.accountId||h.binding.accountId!==input.accountId||p.binding.pursuitId!==input.pursuitId||h.binding.pursuitId!==input.pursuitId)add(issues,"scope_mismatch","binding","Account/Pursuit scope is inconsistent.","invalid");
  if(p.binding.crmRevisionSetSha256!==input.crm.revisionSetSha256||h.binding.crmRevisionSetSha256!==input.crm.revisionSetSha256)add(issues,"stale_crm_revision","crm.revisionSetSha256","CRM revision binding is stale.","stale");
  if(p.selectedRecommendation.intendedDownstreamOperative!=="future CLOSER-01"||!["complete_proof_milestone","pursue_standard_paid_conversion","pursue_repeat_or_retention"].includes(p.selectedRecommendation.family))add(issues,"unsupported_objective","revenue.objective","Objective is not supported by the frozen CLOSER receiver capability.","invalid");
  for(const[field,value,message]of[["growth.sourceEnvelopeId",input.growth.sourceEnvelopeId,"GROWTH source identity is missing."],["growth.sourceEnvelopeSha256",input.growth.sourceEnvelopeSha256,"GROWTH source hash is missing."],["growth.candidateSha256",input.growth.candidateSha256,"GROWTH candidate identity is missing."],["sales.artifactSha256",input.sales.artifactSha256,"SALES artifact identity is missing."],["sales.playbookId",input.sales.playbookId,"SALES Playbook ID is missing."],["sales.playbookVersion",input.sales.playbookVersion,"SALES Playbook version is missing."],["crm.conversationThreadId",input.crm.conversationThreadId,"Canonical conversation thread continuity is missing."],["authority.authorityId",input.authority.authorityId,"Founder authority identity is missing."],["authority.recipientContactId",input.authority.recipientContactId,"Recipient scope is missing."],["authority.channel",input.authority.channel,"Channel scope is missing."],["authority.threadId",input.authority.threadId,"Authority thread scope is missing."]]as const)if(!present(value))add(issues,"required_input_missing",field,message);
  if(input.sales.playbookSuperseded!==false)add(issues,"sales_playbook_not_current","sales.playbookSuperseded","SALES Playbook currency is unknown or superseded.",input.sales.playbookSuperseded?"stale":"missing");
  if(!input.sales.positioning||!input.sales.offerContext||!input.sales.approvedClaims.length)add(issues,"sales_playbook_incomplete","sales","Current positioning, offer context, and approved claims are required.");
  if(!input.crm.participants.length)add(issues,"participant_missing","crm.participants","No authoritative participant is available.");
  if(input.crm.dnc.effectiveExecutionState!=="eligible_for_separate_authorization")add(issues,"dnc_not_clear","crm.dnc","DNC is blocked or requires review; packet readiness fails closed.","blocked");
  if(input.crm.freshness.staleFields.length||input.crm.freshness.unknownFreshnessFields.length)add(issues,"crm_freshness_unresolved","crm.freshness","CRM freshness is stale or unknown.","stale");
  if(input.authority.scope!=="tier0_packet_readiness"||input.authority.executionAuthorized||input.authority.closerInvoked||input.authority.persisted)add(issues,"authority_amplification","authority","Authority exceeds session-only packet readiness.","invalid");
  const authorityCurrent=current(input.generatedAt,input.authority.effectiveAt,input.authority.expiresAt);if(!authorityCurrent)add(issues,"authority_not_current","authority","Founder authority is not currently effective.","stale");
  if(input.authority.recipientContactId&&!input.crm.participants.some(x=>x.contactId===input.authority.recipientContactId))add(issues,"recipient_scope_mismatch","authority.recipientContactId","Authorized recipient is not a canonical participant.","conflicting");
  if(input.authority.threadId&&input.crm.conversationThreadId!==input.authority.threadId)add(issues,"thread_scope_mismatch","authority.threadId","Authority thread scope conflicts with canonical CRM thread.","conflicting");
  const body={schemaVersion:CLOSER_PACKET_SCHEMA,version:CLOSER_PACKET_VERSION,canonicalizationVersion:CLOSER_PACKET_CANONICALIZATION,assemblerVersion:CLOSER_PACKET_ASSEMBLER_VERSION,packetContractSha256:CLOSER_PACKET_CONTRACT_SHA256,generatedAt:input.generatedAt,binding:{accountId:input.accountId,pursuitId:input.pursuitId,conversationThreadId:input.crm.conversationThreadId,crmRevisionSetSha256:input.crm.revisionSetSha256},sourceContracts:{growth:input.growthContract,sales:input.salesContract,crm:input.crmContract,revenue:input.revenueContract,closer:input.closerContract},growth:input.growth,sales:input.sales,crm:input.crm,revenue:{approvedPackageId:p.packageId,approvedPackageSha256:p.packageSha256,objectiveId:p.identities.freshRecommendationId,objectiveVersion:p.identities.recommendationSchemaVersion,objectiveLifecycleState:"APPROVED_PREPARE_ONLY"as const,objectiveFamily:p.selectedRecommendation.family,assignmentType:p.selectedRecommendation.assignmentType,objective:p.selectedRecommendation.objective,priority:input.revenue.priority,timing:input.revenue.timing,proofState:input.revenue.proofState,successCondition:p.successCondition,stopConditions:p.blockers.map(x=>x.description)},authority:input.authority,freshness:{crmRevisionCurrent:!issues.some(x=>x.code==="stale_crm_revision"),salesPlaybookCurrent:input.sales.playbookSuperseded===false,authorityCurrent,packetSuperseded:false as const},issues,completeness:issues.length?"incomplete"as const:"valid"as const,readiness:issues.length?"not_ready"as const:"ready_to_simulate"as const,authorityResult:{maximum:"preview_readiness"as const,closerInvoked:false as const,messageSent:false as const,crmMutation:false as const,providerInvocation:false as const,persisted:false as const,scheduling:false as const,paymentAction:false as const,externalAction:false as const}};
  return{...body,packetId:revenueStableId("closerpkt",body),packetSha256:revenueSha256(body)};
}
