import type{CrmAccountDetailReadModel}from"../crm-01/read-types";
import type{CrmRevenueSnapshotV1}from"../crm-01/revenue-snapshot-types";
import{revenueStableId}from"../revenue-01/canonical";
import type{RevenueRecommendationV1}from"../revenue-01/types";
import type{ApprovedActionPackageV1}from"../revenue-01/approved-action";
import type{WorkforceRoutingPreviewV1}from"../workforce/handoff";
import{assembleConversationIntelligencePacket,CloserPacketError}from"./conversation-intelligence";
import type{CloserFounderAuthorityV1,CloserPacketInput}from"./types";
import type{CurrentSalesPlaybookProjectionV1}from"../crm-01/sales-playbook-artifact";

const GROWTH_SHA="618b895eb97479db83edc668a32bc4db93a222429b27e2a8f6cbadc2bbb7e860";
const SALES_SHA="0428ae67558fb21d288e3588139a8f46d2fdd17cc436b07f7ce1f17f14c265e6";
export function buildSessionAuthority(params:{uid:string;generatedAt:string;packageId:string;recipientContactId:string|null;channel:string|null;threadId:string|null}):CloserFounderAuthorityV1{
  const basis={uid:params.uid,generatedAt:params.generatedAt,packageId:params.packageId,scope:"tier0_packet_readiness"};
  return{authorityId:revenueStableId("closerauth",basis),version:"v1",scope:"tier0_packet_readiness",approvedByUid:params.uid,effectiveAt:params.generatedAt,expiresAt:null,permitted:["validate","assemble","inspect","preview_readiness"],prohibited:["external_messaging","sending","scheduling","crm_mutation","provider_invocation","payment_action","production_mutation","objective_activation","autonomous_downstream_invocation","durable_assignment_acceptance","closer_simulation"],recipientContactId:params.recipientContactId,channel:params.channel,threadId:params.threadId,executionAuthorized:false,closerInvoked:false,persisted:false};
}
export function assembleCloserReadinessFromCanonical(params:{snapshot:CrmRevenueSnapshotV1;detail:CrmAccountDetailReadModel;salesPlaybook:CurrentSalesPlaybookProjectionV1;recommendation:RevenueRecommendationV1;approvedPackage:ApprovedActionPackageV1;routingPreview:WorkforceRoutingPreviewV1;contracts:{growth:{version:string;sha256:string};sales:{version:string;sha256:string};crm:{version:"V1.1";sha256:string};revenue:{version:"V1.1";sha256:string};closer:{version:"V1";sha256:string}};uid:string;generatedAt:string}){
  const{snapshot,detail,recommendation}=params,pursuit=detail.pursuits.find(x=>x.id===snapshot.snapshotIdentity.pursuitId),growth=detail.growthOpportunities.find(x=>x.id===snapshot.upstream.growth.opportunityId)??detail.growthOpportunities[0]??null;
  if(params.contracts.growth.sha256!==GROWTH_SHA||params.contracts.sales.sha256!==SALES_SHA)throw new CloserPacketError("source_contract_drift","Frozen upstream contract identity failed.");
  const playbook=params.salesPlaybook,best=pursuit?.contactSelection.bestFirstContactId??playbook.bestFirstContactId??null,participantIds=new Set(snapshot.interactions.map(x=>x.contactId).filter((x):x is string=>Boolean(x)));if(best)participantIds.add(best);
  const threadId:string|null=null,channel:string|null=null;
  const authority=buildSessionAuthority({uid:params.uid,generatedAt:params.generatedAt,packageId:params.approvedPackage.packageId,recipientContactId:best,channel,threadId});
  const input:CloserPacketInput={generatedAt:params.generatedAt,accountId:snapshot.snapshotIdentity.accountId,pursuitId:snapshot.snapshotIdentity.pursuitId,closerContract:params.contracts.closer,growthContract:params.contracts.growth,salesContract:params.contracts.sales,crmContract:params.contracts.crm,revenueContract:params.contracts.revenue,growth:{sourceEnvelopeId:snapshot.upstream.growth.sourceEnvelopeId,sourceEnvelopeSha256:snapshot.upstream.growth.sourceEnvelopeSha256,candidateSha256:snapshot.upstream.growth.candidateSha256,sourceVersion:playbook.growthSourceVersion,score:snapshot.upstream.growth.score,band:snapshot.upstream.growth.band,confidence:snapshot.upstream.growth.confidence,feasibility:snapshot.upstream.growth.feasibility,brand:growth?.brand??snapshot.account.displayName,productOrEvent:growth?.productOrEvent??null,wedge:growth?.wedge??null,retailerIndependence:snapshot.pursuit.retailerDependencyState.description,unknowns:snapshot.unknowns.filter(x=>x.status!=="resolved").map(x=>x.statement)},sales:{artifactSha256:playbook.artifactSha256,playbookId:playbook.artifactId,playbookVersion:playbook.playbookVersion,playbookSuperseded:playbook.superseded,pursuitDecision:playbook.pursuitDecision,contacts:snapshot.stakeholders.map(x=>({contactId:x.contactId,title:x.currentTitle,strategicRoles:x.strategicRoles,classification:x.roleClassification,buyingAuthority:x.buyingAuthority,freshness:x.freshness,conflicts:x.conflicts})),bestFirstContactId:best,positioning:playbook.positioning,approvedClaims:playbook.approvedClaims.map(x=>({id:x.id,statement:x.statement,classification:x.classification})),offerContext:snapshot.pursuit.selectedEntryOfferId,objections:playbook.objections.map(x=>({objection:x.objection,response:x.response,escalate:x.escalate})),escalationBoundaries:playbook.escalationBoundaries},crm:{revisionSetSha256:snapshot.revisionBinding.revisionSetSha256,conversationThreadId:threadId,participants:[...participantIds].map(contactId=>({contactId,title:snapshot.stakeholders.find(x=>x.contactId===contactId)?.currentTitle??null})),interactions:snapshot.interactions,dnc:snapshot.relationshipSafety,stage:snapshot.pursuit.stage,rightsState:snapshot.pursuit.rightsState,selectedEntryOfferId:snapshot.pursuit.selectedEntryOfferId,offerCatalog:snapshot.offerCatalog,milestones:snapshot.commercialEvidence.milestones,nextAction:snapshot.nextAction,freshness:snapshot.freshness},revenue:{approvedPackage:params.approvedPackage,routingPreview:params.routingPreview,priority:recommendation.economics.priority,timing:recommendation.economics.timing,proofState:recommendation.observedState.proofState},authority};
  return assembleConversationIntelligencePacket(input);
}
