import type{CrmRevenueSnapshotV1}from"../crm-01/revenue-snapshot-types";
import type{ApprovedActionPackageV1}from"../revenue-01/approved-action";
import type{WorkforceRoutingPreviewV1}from"../workforce/handoff";

export const CLOSER_PACKET_SCHEMA="closer-01-conversation-intelligence-packet-v1"as const;
export const CLOSER_PACKET_VERSION="v1"as const;
export const CLOSER_PACKET_CANONICALIZATION="closer-01-conversation-intelligence-canonical-json-v1"as const;
export const CLOSER_PACKET_ASSEMBLER_VERSION="closer-01-packet-assembler-v1"as const;
export type CloserFounderAuthorityV1={authorityId:string;version:"v1";scope:"tier0_packet_readiness";approvedByUid:string;effectiveAt:string;expiresAt:string|null;permitted:["validate","assemble","inspect","preview_readiness"];prohibited:["external_messaging","sending","scheduling","crm_mutation","provider_invocation","payment_action","production_mutation","objective_activation","autonomous_downstream_invocation","durable_assignment_acceptance","closer_simulation"];recipientContactId:string|null;channel:string|null;threadId:string|null;executionAuthorized:false;closerInvoked:false;persisted:false};
export type CloserGrowthContext={sourceEnvelopeId:string|null;sourceEnvelopeSha256:string|null;candidateSha256:string|null;sourceVersion:string|null;score:number|null;band:string|null;confidence:string|null;feasibility:string|null;brand:string|null;productOrEvent:string|null;wedge:string|null;retailerIndependence:string|null;unknowns:string[]};
export type CloserSalesContext={artifactSha256:string|null;playbookId:string|null;playbookVersion:string|null;playbookSuperseded:boolean|null;pursuitDecision:string|null;contacts:Array<{contactId:string;title:string|null;strategicRoles:string[];classification:"sales_inference"|"unavailable";buyingAuthority:"supported"|"unknown";freshness:string|null;conflicts:string[]}>;bestFirstContactId:string|null;positioning:string|null;approvedClaims:Array<{id:string;statement:string;classification:string}>;offerContext:string|null;objections:Array<{objection:string;response:string;escalate:boolean}>;escalationBoundaries:string[]};
export type CloserCrmContext={revisionSetSha256:string;conversationThreadId:string|null;participants:Array<{contactId:string;title:string|null}>;interactions:CrmRevenueSnapshotV1["interactions"];dnc:CrmRevenueSnapshotV1["relationshipSafety"];stage:string|null;rightsState:CrmRevenueSnapshotV1["pursuit"]["rightsState"];selectedEntryOfferId:string|null;offerCatalog:CrmRevenueSnapshotV1["offerCatalog"];milestones:CrmRevenueSnapshotV1["commercialEvidence"]["milestones"];nextAction:CrmRevenueSnapshotV1["nextAction"];freshness:CrmRevenueSnapshotV1["freshness"]};
export type CloserPacketInput={generatedAt:string;accountId:string;pursuitId:string;closerContract:{version:"V1";sha256:string};growthContract:{version:string;sha256:string};salesContract:{version:string;sha256:string};crmContract:{version:"V1.1";sha256:string};revenueContract:{version:"V1.1";sha256:string};growth:CloserGrowthContext;sales:CloserSalesContext;crm:CloserCrmContext;revenue:{approvedPackage:ApprovedActionPackageV1;routingPreview:WorkforceRoutingPreviewV1;priority:string|null;timing:string|null;proofState:string|null};authority:CloserFounderAuthorityV1};
export type CloserPacketIssue={code:string;field:string;message:string;classification:"missing"|"stale"|"conflicting"|"invalid"|"blocked"};
export type ConversationIntelligencePacketV1={schemaVersion:typeof CLOSER_PACKET_SCHEMA;version:typeof CLOSER_PACKET_VERSION;canonicalizationVersion:typeof CLOSER_PACKET_CANONICALIZATION;assemblerVersion:typeof CLOSER_PACKET_ASSEMBLER_VERSION;packetContractSha256:string;packetId:string;packetSha256:string;generatedAt:string;binding:{accountId:string;pursuitId:string;conversationThreadId:string|null;crmRevisionSetSha256:string};sourceContracts:{growth:CloserPacketInput["growthContract"];sales:CloserPacketInput["salesContract"];crm:CloserPacketInput["crmContract"];revenue:CloserPacketInput["revenueContract"];closer:CloserPacketInput["closerContract"]};growth:CloserGrowthContext;sales:CloserSalesContext;crm:CloserCrmContext;revenue:{approvedPackageId:string;approvedPackageSha256:string;objectiveId:string;objectiveVersion:string;objectiveLifecycleState:"APPROVED_PREPARE_ONLY";objectiveFamily:string;assignmentType:string;objective:string;priority:string|null;timing:string|null;proofState:string|null;successCondition:string;stopConditions:string[]};authority:CloserFounderAuthorityV1;freshness:{crmRevisionCurrent:boolean;salesPlaybookCurrent:boolean;authorityCurrent:boolean;packetSuperseded:false};issues:CloserPacketIssue[];completeness:"valid"|"incomplete";readiness:"ready_to_simulate"|"not_ready";authorityResult:{maximum:"preview_readiness";closerInvoked:false;messageSent:false;crmMutation:false;providerInvocation:false;persisted:false;scheduling:false;paymentAction:false;externalAction:false}};
