import assert from"node:assert/strict";import test from"node:test";
import{buildApprovedActionPackage,APPROVED_ACTION_PACKAGE_CONTRACT,APPROVED_ACTION_PACKAGE_CONTRACT_SHA256,APPROVED_ACTION_PACKAGE_SCHEMA,RevenueApprovalError}from"../../lib/agents/revenue-01/approved-action.ts";import{revenueSha256}from"../../lib/agents/revenue-01/canonical.ts";import{COMMERCIAL_GOAL_BODY,COMMERCIAL_GOAL_SHA256}from"../../lib/agents/revenue-01/commercial-goals.ts";import{buildRevenueRecommendation}from"../../lib/agents/revenue-01/recommendation.ts";import{AT,REVENUE_SHA,runContext,snapshot}from"./fixtures.mjs";
const recommendation=(s=snapshot())=>buildRevenueRecommendation({snapshot:s,runContext:runContext(),revenueContract:{version:"V1.1",sha256:REVENUE_SHA},commercialGoal:{goalId:COMMERCIAL_GOAL_BODY.goalId,version:COMMERCIAL_GOAL_BODY.version,sha256:COMMERCIAL_GOAL_SHA256},generatedAt:AT});
const build=(r,family=r.recommendation.family,revision=r.binding.crmRevisionSetSha256)=>buildApprovedActionPackage({recommendation:r,selectedFamily:family,displayedRecommendationId:"revrec_displayed",expectedRevisionSetSha256:revision,approvedByUid:"founder",approvedAt:AT});
test("server-derived primary approval creates an immutable prepare-only package",()=>{const r=recommendation(),p=build(r);assert.equal(p.schemaVersion,APPROVED_ACTION_PACKAGE_SCHEMA);assert.equal(APPROVED_ACTION_PACKAGE_CONTRACT_SHA256,revenueSha256(APPROVED_ACTION_PACKAGE_CONTRACT));assert.equal(p.schemaContractSha256,APPROVED_ACTION_PACKAGE_CONTRACT_SHA256);assert.equal(p.status,"APPROVED");assert.equal(p.handoffPackageState,"CREATED");assert.equal(p.selectedRecommendation.family,r.recommendation.family);assert.equal(p.binding.crmSnapshotSha256,r.binding.crmSnapshotSha256);assert.deepEqual(p.authority.capabilities,{recommend:true,prepare:true,requestApproval:false,execute:false});assert.deepEqual(p.authority.permitted,["prepare"]);assert.equal(p.authority.executionAuthorized,false);assert.equal(p.authority.downstreamInvocationAuthorized,false);assert.equal(p.persistence.persisted,false);assert.ok(p.packageId&&p.packageSha256);});
test("eligible engine alternative can be approved but unsupported destination remains null",()=>{const milestones=["paid_offer_accepted","payment_collected","repeat_purchase_interest"].map(type=>({milestoneId:type,type,occurredAt:AT,summary:type,verification:"verified",productionReference:null,evidence:[{id:`e-${type}`,classification:"verified_fact",source:"fixture",statement:type,observedAt:AT,evidenceUrl:null}]}));const r=recommendation(snapshot({engaged:true,accepted:"supported",publication:"supported",scan:"supported",rights:"confirmed",offer:"irl-retail-media-product-2",paymentAvailability:"available",milestones}));const alternative=r.alternatives[0];assert.ok(alternative);const p=build(r,alternative.family);assert.equal(p.selectedRecommendation.selection,"alternative");assert.equal(p.selectedRecommendation.intendedDownstreamOperative,null);});
test("stale revision binding and no-longer-eligible selections fail closed",()=>{const r=recommendation();assert.throws(()=>build(r,r.recommendation.family,"a".repeat(64)),e=>e instanceof RevenueApprovalError&&e.code==="stale_recommendation");assert.throws(()=>build(r,"pursue_standard_paid_conversion"),e=>e instanceof RevenueApprovalError&&e.code==="recommendation_no_longer_eligible");});
test("approval cannot bypass paid-conversion proof and rights prerequisites",()=>{const r=recommendation(snapshot({engaged:true,accepted:"supported",publication:"unknown",scan:"unknown",rights:"unknown",offer:"irl-retail-media-product-2",milestones:[{milestoneId:"paid",type:"paid_offer_accepted",occurredAt:AT,summary:"paid",verification:"verified",productionReference:null,evidence:[{id:"e",classification:"verified_fact",source:"fixture",statement:"paid",observedAt:AT,evidenceUrl:null}]}]}));assert.equal(r.deterministicAssessment.eligibility.find(x=>x.family==="pursue_standard_paid_conversion").eligible,false);assert.throws(()=>build(r,"pursue_standard_paid_conversion"),RevenueApprovalError);});
test("same authoritative approval input produces the same package identity",()=>{const r=recommendation();assert.deepEqual(build(r),build(r));});
