import assert from "node:assert/strict";
import test from "node:test";
import { readFile, access } from "node:fs/promises";

const routePath="app/api/admin/agents/revenue-01/recommend/route.ts";
const pagePath="app/admin/revenue-01/page.tsx";

test("recommendation route is POST-only, Admin-authorized and no-store",async()=>{const route=await readFile(routePath,"utf8");assert.match(route,/export async function POST/);assert.doesNotMatch(route,/export async function (GET|PUT|PATCH|DELETE)/);assert.match(route,/authorizeCrmAdmin\(request/);assert.match(route,/verifyIdToken/);assert.match(route,/isAdmin/);assert.match(route,/Cache-Control.*no-store/);assert.ok(route.indexOf("authorizeCrmAdmin(request")<route.indexOf("getCrmRevenueSnapshot({"));});
test("route validates identifiers and exact Founder context without accepting a client snapshot",async()=>{const route=await readFile(routePath,"utf8");assert.match(route,/\^\[A-Za-z0-9_-\]\{1,128\}\$/);assert.match(route,/exactKeys\(body, \["accountId", "pursuitId", "runContext"\]\)/);assert.match(route,/normalizeRevenueRunContext/);assert.doesNotMatch(route,/body\.snapshot|input\.snapshot|clientSnapshot/);});
test("fresh CRM snapshot and integrity checks precede the deterministic engine",async()=>{const route=await readFile(routePath,"utf8");const revenueCheck=route.indexOf("await loadRevenueContractMetadata(now)"),goalCheck=route.indexOf("COMMERCIAL_GOAL_SHA256 !== APPROVED_GOAL_SHA256"),crmCheck=route.indexOf("await loadCrmContractMetadata(now)"),snapshot=route.indexOf("getCrmRevenueSnapshot({"),engine=route.indexOf("createDeterministicRevenueRecommendation({");assert.ok(revenueCheck<goalCheck&&goalCheck<crmCheck&&crmCheck<snapshot&&snapshot<engine);assert.match(route,/snapshotIdentity\.accountId !== input\.accountId/);assert.match(route,/snapshotIdentity\.pursuitId !== input\.pursuitId/);});
test("Phase 1A.2 has no provider, persistence, CRM write, CLOSER, messaging, payment or scheduler authority",async()=>{const route=await readFile(routePath,"utf8"),page=await readFile(pagePath,"utf8"),all=route+page;assert.doesNotMatch(all,/OpenAI|provider\.research|stripe|sendEmail|postmark|resend|schedule|setInterval|runTransaction|\.set\(|\.add\(|\.update\(|localStorage|sessionStorage|csv|download/i);assert.doesNotMatch(all,/invokeCloser|sendToCloser|approveRecommendation|crmMutation\s*:\s*true/i);assert.match(route,/persisted: false/);});
test("no Revenue persistence or provider surface exists",async()=>{await assert.rejects(access("lib/agents/revenue-01/providers"));await assert.rejects(access("lib/agents/revenue-01/firestore.ts"));});
