import assert from"node:assert/strict";import test from"node:test";
import{COMMERCIAL_GOAL_BODY,COMMERCIAL_GOAL_SHA256}from"../../lib/agents/revenue-01/commercial-goals.ts";import{buildRevenueRecommendation}from"../../lib/agents/revenue-01/recommendation.ts";import{RevenueValidationError}from"../../lib/agents/revenue-01/validation.ts";import{AT,REVENUE_SHA,runContext,snapshot}from"./fixtures.mjs";
const input=(s=snapshot(),context=runContext())=>({snapshot:s,runContext:context,revenueContract:{version:"V1.1",sha256:REVENUE_SHA},commercialGoal:{goalId:COMMERCIAL_GOAL_BODY.goalId,version:COMMERCIAL_GOAL_BODY.version,sha256:COMMERCIAL_GOAL_SHA256},generatedAt:AT});
test("malformed CRM and catalog identities fail closed",()=>{for(const mutate of[s=>s.crmContract.sha256="wrong",s=>s.offerCatalog.sha256="wrong",s=>s.schemaVersion="wrong"]){const s=snapshot();mutate(s);assert.throws(()=>buildRevenueRecommendation(input(s)),RevenueValidationError);}});
test("Account and Pursuit identity mismatches fail closed",()=>{assert.throws(()=>buildRevenueRecommendation(input(snapshot({accountRecordId:"other"}))),/Account\/Pursuit/);assert.throws(()=>buildRevenueRecommendation(input(snapshot({salesPursuitId:"other"}))),/Account\/Pursuit/);});
test("malformed revision binding fails closed",()=>{const s=snapshot();s.revisionBinding.records[0].revision=0;assert.throws(()=>buildRevenueRecommendation(input(s)),/revision binding/);const missing=snapshot();missing.revisionBinding.records=[];assert.throws(()=>buildRevenueRecommendation(input(missing)),/revision binding/);});
test("Free First $0 and nonrevenue invariant fails closed on drift",()=>{assert.throws(()=>buildRevenueRecommendation(input(snapshot({freePrice:1}))),/Free First/);assert.throws(()=>buildRevenueRecommendation(input(snapshot({freeRevenue:true}))),/Free First/);});
test("run context is normalized and cannot promote a missing baseline",()=>{assert.throws(()=>buildRevenueRecommendation(input(snapshot(),{...runContext(),reportingMonth:"2026-13"})),/Reporting month/);assert.throws(()=>buildRevenueRecommendation(input(snapshot(),runContext(null,"founder_supplied_unverified"))),/missing Founder baseline/);});
test("REVENUE contract and company-goal identity mismatches fail closed",()=>{assert.throws(()=>buildRevenueRecommendation({...input(),revenueContract:{version:"V1.1",sha256:"wrong"}}),/REVENUE contract/);assert.throws(()=>buildRevenueRecommendation({...input(),commercialGoal:{goalId:COMMERCIAL_GOAL_BODY.goalId,version:"v1",sha256:"wrong"}}),/Commercial goal/);});
