import type { Firestore } from "firebase-admin/firestore";
import { crmSha256, crmStableId } from "./canonical";
import { verifyMutationApproval } from "./mutation-approval";
import { buildCrmMutationPlan, mutationReadPaths } from "./mutation-planner";
import type { CrmFounderMutationPacket, CrmMutationApproval, CrmMutationPlan, CrmMutationReceipt, CrmRevisionRecord } from "./mutation-types";
import { CrmMutationError } from "./mutation-validation";
import type { CrmStoredRecord } from "./types";

export async function loadMutationRecords(db:Firestore,packet:CrmFounderMutationPacket):Promise<Record<string,CrmStoredRecord>> { const paths=mutationReadPaths(packet.mutation); const snaps=paths.length?await db.getAll(...paths.map(path=>db.doc(path))):[]; const records:Record<string,CrmStoredRecord>={};snaps.forEach((snap,index)=>{if(snap.exists)records[paths[index]]=snap.data() as CrmStoredRecord;});return records; }

export async function commitCrmMutation(params:{db:Firestore;packet:CrmFounderMutationPacket;submittedPlan:CrmMutationPlan;approval:CrmMutationApproval;uid:string;crmContractSha256:string;at:string}):Promise<CrmMutationReceipt>{const {db,packet,submittedPlan,approval,uid,crmContractSha256,at}=params;const receiptRef=db.doc(`crm/mutations/records/${packet.idempotencyKey}`);return db.runTransaction(async(transaction)=>{const receiptSnap=await transaction.get(receiptRef);if(receiptSnap.exists){const receipt=receiptSnap.data() as CrmMutationReceipt;if(receipt.packetSha256!==packet.packetSha256)throw new CrmMutationError("idempotency_conflict","Idempotency key was already used for a different mutation.");return {...receipt,replayed:true};}const paths=mutationReadPaths(packet.mutation);const snaps=paths.length?await transaction.getAll(...paths.map(path=>db.doc(path))):[];const records:Record<string,CrmStoredRecord>={};snaps.forEach((snap,index)=>{if(snap.exists)records[paths[index]]=snap.data() as CrmStoredRecord;});let current:CrmMutationPlan;try{current=buildCrmMutationPlan({packet,records,crmContractSha256});}catch(error){throw new CrmMutationError("revision_conflict",error instanceof Error?error.message:"Canonical CRM state changed after preview.");}if(current.planSha256!==submittedPlan.planSha256)throw new CrmMutationError("revision_conflict","Canonical CRM state changed after preview.");verifyMutationApproval(current,approval,uid);const receiptId=crmStableId("mutation",{idempotencyKey:packet.idempotencyKey,packetSha256:packet.packetSha256});const revisionPaths:string[]=[];for(const op of current.operations){const revision:CrmRevisionRecord={schemaVersion:"crm-revision-v1",revisionId:op.revisionPath.split("/").at(-1)!,recordPath:op.path,entityType:op.entityType,mutationKind:packet.mutation.kind,before:op.before,after:op.after,beforeSha256:op.beforeSha256,afterSha256:op.afterSha256,priorRevision:op.expectedRevision,resultingRevision:op.after.revision,changedFields:op.changedFields,evidence:packet.mutation.evidence,actorUid:uid,effectiveAt:"effectiveAt" in packet.mutation?String(packet.mutation.effectiveAt):"occurredAt" in packet.mutation?String(packet.mutation.occurredAt):null,recordedAt:at,correctionOfRevision:packet.mutation.kind==="correct_record"?packet.mutation.correctionOfRevision:null,supersedesRevision:packet.mutation.kind==="correct_record"?packet.mutation.correctionOfRevision:null,packetSha256:packet.packetSha256,planSha256:current.planSha256,receiptId};transaction.create(db.doc(op.revisionPath),revision);transaction.set(db.doc(op.path),op.after);revisionPaths.push(op.revisionPath);}const receipt:CrmMutationReceipt={schemaVersion:"crm-mutation-receipt-v1",receiptId,idempotencyKey:packet.idempotencyKey,packetSha256:packet.packetSha256,planSha256:current.planSha256,committedAt:at,committedByUid:uid,recordPaths:current.operations.map(x=>x.path),revisionPaths,replayed:false};transaction.create(receiptRef,receipt);return receipt;});}

export class InMemoryMutationRepository { records=new Map<string,CrmStoredRecord>(); revisions=new Map<string,CrmRevisionRecord>(); receipts=new Map<string,CrmMutationReceipt>(); commit(packet:CrmFounderMutationPacket,plan:CrmMutationPlan,approval:CrmMutationApproval,uid:string,contractSha:string,at:string):CrmMutationReceipt {const old=this.receipts.get(packet.idempotencyKey);if(old){if(old.packetSha256!==packet.packetSha256)throw new CrmMutationError("idempotency_conflict","Idempotency conflict.");return {...old,replayed:true};}const current=buildCrmMutationPlan({packet,records:Object.fromEntries(this.records),crmContractSha256:contractSha});if(current.planSha256!==plan.planSha256)throw new CrmMutationError("revision_conflict","Canonical state changed.");verifyMutationApproval(current,approval,uid);const receiptId=crmStableId("mutation",packet.packetSha256),revisionPaths:string[]=[];for(const op of current.operations){const revision={schemaVersion:"crm-revision-v1" as const,revisionId:op.revisionPath.split("/").at(-1)!,recordPath:op.path,entityType:op.entityType,mutationKind:packet.mutation.kind,before:op.before,after:op.after,beforeSha256:op.beforeSha256,afterSha256:op.afterSha256,priorRevision:op.expectedRevision,resultingRevision:op.after.revision,changedFields:op.changedFields,evidence:packet.mutation.evidence,actorUid:uid,effectiveAt:null,recordedAt:at,correctionOfRevision:packet.mutation.kind==="correct_record"?packet.mutation.correctionOfRevision:null,supersedesRevision:null,packetSha256:packet.packetSha256,planSha256:current.planSha256,receiptId};this.records.set(op.path,op.after);this.revisions.set(op.revisionPath,revision);revisionPaths.push(op.revisionPath);}const receipt={schemaVersion:"crm-mutation-receipt-v1" as const,receiptId,idempotencyKey:packet.idempotencyKey,packetSha256:packet.packetSha256,planSha256:current.planSha256,committedAt:at,committedByUid:uid,recordPaths:current.operations.map(x=>x.path),revisionPaths,replayed:false};this.receipts.set(packet.idempotencyKey,receipt);return receipt;}}
