import type { CrmEntityType, CrmProvenance, CrmStage, CrmStoredRecord } from "./types";

export const CRM_MUTATION_KINDS = ["correct_record", "add_evidence", "record_interaction", "record_founder_decision", "transition_pursuit", "update_dnc", "set_next_action", "create_attention_item", "transition_attention_item", "record_milestone"] as const;
export type CrmMutationKind = typeof CRM_MUTATION_KINDS[number];
export type CrmDisposition = "Active" | "Nurture / Revisit" | "Not Pursued" | "Closed";
export type CrmDncScope = "account" | "contact" | "channel";
export type CrmDncState = "active" | "inactive" | "unknown" | "conflicting";

export type CrmEvidenceInput = { id: string; classification: CrmProvenance; source: string; statement: string; observedAt: string | null; evidenceUrl: string | null };
export type CrmNextAction = { actionId: string; type: string; description: string; accountId: string; pursuitId: string | null; contactId: string | null; owner: "Founder"; status: "open" | "completed" | "cancelled"; dueAt: string | null; timingBasis: string | null; approvalRequired: boolean; executionAuthorized: false; sourceEvidenceIds: string[]; completionEvidenceIds: string[] };
export type CrmConversationParticipant = { type: "crm_contact"; id: string } | { type: "goshsha_internal"; id: "goshsha_founder" };
export type CrmProviderReference = { provider: string; externalMessageId: string | null; externalThreadId: string | null; externalConversationId: string | null; evidenceIds: string[] };
export type CrmConversationInput = { participants: CrmConversationParticipant[]; senderParticipantKey: string | null; recipientParticipantKeys: string[]; channel: "email" | "linkedin" | "sms" | "phone" | "meeting" | "other" | null; replyToInteractionId: string | null; providerReference: CrmProviderReference | null; evidenceIds: string[] };

export type CrmMutationPayload =
  | { kind: "correct_record"; targetEntityType: "account" | "contact" | "salesPursuit"; targetRecordId: string; field: "displayName" | "relationshipStatus" | "name" | "currentTitle" | "contactRoute" | "buyingAuthority"; correctedValue: unknown; correctionOfRevision: number; reason: string; evidence: CrmEvidenceInput[] }
  | { kind: "add_evidence"; targetEntityType: "account" | "contact" | "salesPursuit"; targetRecordId: string; evidence: CrmEvidenceInput[]; resolvesState: "none" | "unknown" | "conflicting" }
  | { kind: "record_interaction"; accountId: string; pursuitId: string | null; contactId: string | null; interactionType: "outbound_sent" | "inbound_received" | "meeting" | "manual_note"; exactStatement: string | null; summary: string; occurredAt: string; conversation?: CrmConversationInput | null; evidence: CrmEvidenceInput[] }
  | { kind: "record_founder_decision"; accountId: string; pursuitId: string | null; decisionType: string; decision: string; rationale: string; effectiveAt: string; evidence: CrmEvidenceInput[] }
  | { kind: "transition_pursuit"; accountId: string; pursuitId: string; toStage: CrmStage | null; toDisposition: CrmDisposition | null; transitionType: "new_event" | "correction"; reason: string; evidence: CrmEvidenceInput[]; productionReference: { type: string; id: string; status: "pending" | "verified" } | null }
  | { kind: "update_dnc"; accountId: string; pursuitId: string | null; contactId: string | null; channel: string | null; scope: CrmDncScope; state: CrmDncState; changeType: "new_evidence" | "correction" | "documented_resolution"; reason: string; effectiveAt: string; expiresAt: string | null; evidence: CrmEvidenceInput[] }
  | { kind: "set_next_action"; accountId: string; pursuitId: string; nextAction: CrmNextAction; evidence: CrmEvidenceInput[] }
  | { kind: "create_attention_item"; accountId: string; pursuitId: string | null; contactId: string | null; attentionType: "reminder" | "condition_alert"; reason: string; priority: "low" | "normal" | "medium" | "high" | "critical"; dueAt: string | null; triggeringCondition: string | null; evidence: CrmEvidenceInput[] }
  | { kind: "transition_attention_item"; accountId: string; attentionItemId: string; toStatus: "open" | "snoozed" | "resolved" | "dismissed"; reason: string; evidence: CrmEvidenceInput[] }
  | { kind: "record_milestone"; accountId: string; pursuitId: string; milestoneType: "free_first_accepted" | "free_first_published" | "physical_scan_verified" | "content_rights_confirmed" | "non_payment_other"; summary: string; occurredAt: string; productionReference: { type: string; id: string; status: "pending" | "verified" } | null; evidence: CrmEvidenceInput[] };

export type CrmMutationClientRequest = { idempotencyKey: string; expectedRevisions: Record<string, number>; mutation: CrmMutationPayload };
export type CrmFounderMutationPacket = { schemaVersion: "crm-founder-mutation-v1"; idempotencyKey: string; requestedByUid: string; requestedAt: string; expectedRevisions: Record<string, number>; mutation: CrmMutationPayload; authority: { outreach: false; campaigns: false; payments: false; revenueInvocation: false; closerInvocation: false; externalAction: false; executionAuthorized: false }; packetSha256: string };
export type CrmMutationOperation = { path: string; entityType: CrmEntityType; expectedRevision: number | null; before: CrmStoredRecord | null; after: CrmStoredRecord; changedFields: string[]; revisionPath: string; beforeSha256: string | null; afterSha256: string };
export type CrmMutationPlan = { schemaVersion: "crm-mutation-plan-v1"; crmContractSha256: string; packetSha256: string; idempotencyKey: string; operations: CrmMutationOperation[]; expectedRevisions: Record<string, number | null>; warnings: string[]; conflicts: string[]; authority: CrmFounderMutationPacket["authority"]; planSha256: string };
export type CrmMutationApproval = { approved: true; scope: "crm_ingestion"; transactionType: "canonical_mutation"; approvedByUid: string; approvedAt: string; packetSha256: string; mutationPlanSha256: string; idempotencyKey: string; expectedRevisions: Record<string, number | null>; authority: CrmFounderMutationPacket["authority"] };
export type CrmRevisionRecord = { schemaVersion: "crm-revision-v1"; revisionId: string; recordPath: string; entityType: CrmEntityType; mutationKind: CrmMutationKind; before: CrmStoredRecord | null; after: CrmStoredRecord; beforeSha256: string | null; afterSha256: string; priorRevision: number | null; resultingRevision: number; changedFields: string[]; evidence: CrmEvidenceInput[]; actorUid: string; effectiveAt: string | null; recordedAt: string; correctionOfRevision: number | null; supersedesRevision: number | null; packetSha256: string; planSha256: string; receiptId: string };
export type CrmMutationReceipt = { schemaVersion: "crm-mutation-receipt-v1"; receiptId: string; idempotencyKey: string; packetSha256: string; planSha256: string; committedAt: string; committedByUid: string; recordPaths: string[]; revisionPaths: string[]; replayed: boolean };
