import { crmSha256, crmStableId } from "./canonical";
import { evaluateDnc } from "./planner";
import type { CrmFounderMutationPacket, CrmMutationOperation, CrmMutationPlan, CrmMutationPayload } from "./mutation-types";
import type { CrmEntityType, CrmStage, CrmStoredRecord } from "./types";

const COLLECTIONS: Record<CrmEntityType,string>={account:"accounts",contact:"contacts",growthOpportunity:"growthOpportunities",salesPursuit:"salesPursuits",interaction:"interactions",decision:"decisions",milestone:"milestones",attentionItem:"attentionItems"};
export const crmRecordPath=(entityType:CrmEntityType,id:string)=>`crm/${COLLECTIONS[entityType]}/records/${id}`;
const object=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"&&!Array.isArray(value)?structuredClone(value as Record<string,unknown>):{};
const evidence=(mutation:CrmMutationPayload)=>mutation.evidence;
const stageOrder:CrmStage[]=["Growth Qualified","Sales Prepared","Founder Review","Outreach Approved","Contacted","Engaged","Conversation Active","Free First Planned","Free First Live","Scan Verified","Paid Customer","Expansion / Recurring","Closed"];

function requireRecord(records:Record<string,CrmStoredRecord>,path:string):CrmStoredRecord { const record=records[path]; if(!record) throw new Error(`Canonical CRM record not found: ${path}`); return record; }
function stageEvidenceAllowed(from:CrmStage,to:CrmStage,mutation:Extract<CrmMutationPayload,{kind:"transition_pursuit"}>):boolean {
  if(to==="Paid Customer"||to==="Expansion / Recurring") return false;
  if(mutation.transitionType==="correction") return mutation.evidence.length>0;
  if(stageOrder.indexOf(to)!==stageOrder.indexOf(from)+1&&to!=="Closed") return false;
  const text=mutation.evidence.map((x)=>`${x.classification} ${x.statement}`).join(" ").toLowerCase();
  if(to==="Contacted") return /sent|delivered|outbound/.test(text)&&!/draft|approval only/.test(text);
  if(to==="Engaged") return /inbound|replied|response/.test(text)&&!/open only|delivery only/.test(text);
  if(to==="Conversation Active") return /conversation|meeting|substantive/.test(text);
  if(to==="Free First Planned") return /accept|planning|agreed to try/.test(text)&&!/recommendation only/.test(text);
  if(to==="Free First Live") return mutation.productionReference?.status==="verified"&&/publish|live/.test(text);
  if(to==="Scan Verified") return /physical scan|scan verified|scanned/.test(text);
  return true;
}
function recordFrom(prior:CrmStoredRecord|null,entityType:CrmEntityType,id:string,data:Record<string,unknown>,packet:CrmFounderMutationPacket,event:string):CrmStoredRecord { const revision=(prior?.revision??0)+1; return {recordSchemaVersion:"crm-record-v1",id,entityType,revision,createdAt:prior?.createdAt??packet.requestedAt,updatedAt:packet.requestedAt,data,provenance:[...new Set([...(prior?.provenance??[]),...evidence(packet.mutation).map((x)=>x.classification)])],history:[...(prior?.history??[]),{revision,event,artifactSha256:packet.packetSha256,at:packet.requestedAt}]}; }
function fieldHash(value:unknown):string{return crmSha256(value===undefined?{__crmMissing:true}:value);}
function changed(before:CrmStoredRecord|null,after:CrmStoredRecord):string[]{ if(!before)return Object.keys(after.data).sort(); const keys=new Set([...Object.keys(before.data),...Object.keys(after.data)]); return [...keys].filter((key)=>fieldHash(before.data[key])!==fieldHash(after.data[key])).sort(); }
function operation(prior:CrmStoredRecord|null,after:CrmStoredRecord,packet:CrmFounderMutationPacket):CrmMutationOperation { const path=crmRecordPath(after.entityType,after.id); return {path,entityType:after.entityType,expectedRevision:prior?.revision??null,before:prior,after,changedFields:changed(prior,after),revisionPath:`crm/revisions/records/${crmStableId("rev",{packet:packet.packetSha256,path,resultingRevision:after.revision})}`,beforeSha256:prior?crmSha256(prior):null,afterSha256:crmSha256(after)}; }
function ensureExpected(packet:CrmFounderMutationPacket,ops:CrmMutationOperation[],records:Record<string,CrmStoredRecord>){for(const path of mutationReadPaths(packet.mutation)){const record=records[path];if(!record)throw new Error(`Canonical CRM record not found: ${path}`);if(packet.expectedRevisions[path]!==record.revision)throw new Error(`Expected revision is missing or stale for ${path}.`);}for(const op of ops)if(!op.before&&packet.expectedRevisions[op.path]!==undefined)throw new Error(`Unexpected revision supplied for new record ${op.path}.`);}

export function mutationReadPaths(m:CrmMutationPayload):string[]{ const paths=new Set<string>(); const add=(type:CrmEntityType,id:string|null)=>{if(id)paths.add(crmRecordPath(type,id));}; if("accountId" in m)add("account",m.accountId); if("pursuitId" in m)add("salesPursuit",m.pursuitId); if("contactId" in m)add("contact",m.contactId); if(m.kind==="correct_record"||m.kind==="add_evidence")add(m.targetEntityType,m.targetRecordId); if(m.kind==="transition_attention_item")add("attentionItem",m.attentionItemId); return [...paths]; }

export function buildCrmMutationPlan(params:{packet:CrmFounderMutationPacket;records:Record<string,CrmStoredRecord>;crmContractSha256:string}):CrmMutationPlan {
 const {packet,records,crmContractSha256}=params; const m=packet.mutation; const ops:CrmMutationOperation[]=[]; const warnings:string[]=[]; const conflicts:string[]=[];
 const update=(type:CrmEntityType,id:string,transform:(data:Record<string,unknown>,prior:CrmStoredRecord)=>Record<string,unknown>)=>{const path=crmRecordPath(type,id),prior=requireRecord(records,path),after=recordFrom(prior,type,id,transform(object(prior.data),prior),packet,m.kind);ops.push(operation(prior,after,packet));};
 const create=(type:CrmEntityType,id:string,data:Record<string,unknown>)=>{const path=crmRecordPath(type,id),prior=records[path]??null;if(prior)throw new Error(`Record already exists: ${path}`);ops.push(operation(null,recordFrom(null,type,id,data,packet,m.kind),packet));};
 if(m.kind==="correct_record") update(m.targetEntityType,m.targetRecordId,(data)=>({...data,[m.field]:m.correctedValue,correction:{reason:m.reason,correctionOfRevision:m.correctionOfRevision,evidenceIds:m.evidence.map(x=>x.id)}}));
 else if(m.kind==="add_evidence") update(m.targetEntityType,m.targetRecordId,(data)=>({...data,evidenceLedger:[...(Array.isArray(data.evidenceLedger)?data.evidenceLedger:[]),...m.evidence],evidenceResolution:m.resolvesState}));
 else if(m.kind==="record_interaction") create("interaction",crmStableId("interaction",{packet:packet.packetSha256}),{accountId:m.accountId,pursuitId:m.pursuitId,contactId:m.contactId,type:m.interactionType,exactStatement:m.exactStatement,summary:m.summary,occurredAt:m.occurredAt,recordedAt:packet.requestedAt,evidence:m.evidence,contacted:m.interactionType==="outbound_sent"});
 else if(m.kind==="record_founder_decision") create("decision",crmStableId("decision",{packet:packet.packetSha256}),{accountId:m.accountId,pursuitId:m.pursuitId,type:m.decisionType,decision:m.decision,rationale:m.rationale,effectiveAt:m.effectiveAt,recordedAt:packet.requestedAt,evidence:m.evidence,doesNotAuthorizeExternalAction:true});
 else if(m.kind==="transition_pursuit") update("salesPursuit",m.pursuitId,(data)=>{const from=String(data.stage??"") as CrmStage;if(m.toStage&&!stageEvidenceAllowed(from,m.toStage,m))throw new Error("Pipeline transition lacks the required authoritative evidence or is outside Phase 1B.2a.");return {...data,stage:m.toStage??data.stage,disposition:m.toDisposition??data.disposition,lastTransition:{fromStage:from,toStage:m.toStage,type:m.transitionType,reason:m.reason,evidenceIds:m.evidence.map(x=>x.id),productionReference:m.productionReference},paymentVerified:false};});
 else if(m.kind==="update_dnc"){const targetType=m.scope==="account"?"account":"contact",targetId=m.scope==="account"?m.accountId:m.contactId!;const accountData=object(requireRecord(records,crmRecordPath("account",m.accountId)).data);const accountDnc=object(accountData.dnc);update(targetType,targetId,(data)=>{const ledger=Array.isArray(data.dncEvidenceLedger)?data.dncEvidenceLedger:[];const status=m.state;const priorContact=object(data.dnc);const priorState=String(priorContact.status??data.dnc??"unknown");if(priorState==="active"&&status==="inactive"){const authoritative=m.evidence.some(item=>item.classification==="future_brand_statement"||item.classification==="production_system_reference"||(item.classification==="founder_provided_information"&&Boolean(item.evidenceUrl)));if((m.changeType!=="correction"&&m.changeType!=="documented_resolution")||!authoritative)throw new Error("Active DNC may become inactive only through evidence-backed correction or documented resolution of the canonical record.");}const accountState=m.scope==="account"?status:String(accountDnc.status??accountData.dnc??"unknown") as "active"|"inactive"|"unknown"|"conflicting";const contactState=m.scope==="contact"?status:String(priorContact.status??data.dnc??"unknown") as "active"|"inactive"|"unknown"|"conflicting";const channelState=m.scope==="channel"?(status==="active"?"suppressed":status==="inactive"?"allowed":status):"unknown";return {...data,dnc:{status,scope:m.scope,channel:m.channel,reason:m.reason,evidenceRefs:m.evidence.map(x=>x.id),effectiveAt:m.effectiveAt,expiresAt:m.expiresAt,changeType:m.changeType},dncEvidenceLedger:[...ledger,{...m,recordedAt:packet.requestedAt}],dncEvaluation:evaluateDnc({account:accountState,contact:targetType==="contact"?contactState:"inactive",channel:channelState})};});}
 else if(m.kind==="set_next_action") update("salesPursuit",m.pursuitId,(data)=>({...data,nextAction:m.nextAction,nextActionEvidence:m.evidence}));
 else if(m.kind==="create_attention_item") create("attentionItem",crmStableId("attention",{packet:packet.packetSha256}),{accountId:m.accountId,pursuitId:m.pursuitId,contactId:m.contactId,type:m.attentionType,reason:m.reason,priority:m.priority,dueAt:m.dueAt,owner:"Founder",status:"open",triggeringCondition:m.triggeringCondition,evidence:m.evidence,executionAuthorized:false});
 else if(m.kind==="transition_attention_item") update("attentionItem",m.attentionItemId,(data)=>({...data,status:m.toStatus,statusReason:m.reason,statusEvidence:m.evidence}));
 else create("milestone",crmStableId("milestone",{packet:packet.packetSha256}),{accountId:m.accountId,pursuitId:m.pursuitId,type:m.milestoneType,summary:m.summary,occurredAt:m.occurredAt,recordedAt:packet.requestedAt,productionReference:m.productionReference,evidence:m.evidence,freeFirstRevenueUsd:0,paymentVerified:false});
 ensureExpected(packet,ops,records); const expectedRevisions=Object.fromEntries([...mutationReadPaths(m).map(path=>[path,records[path]?.revision??null] as const),...ops.filter(op=>!records[op.path]).map(op=>[op.path,null] as const)]); const body={schemaVersion:"crm-mutation-plan-v1" as const,crmContractSha256,packetSha256:packet.packetSha256,idempotencyKey:packet.idempotencyKey,operations:ops,expectedRevisions,warnings,conflicts,authority:packet.authority}; return {...body,planSha256:crmSha256(body)};
}
