"use client";
import { useMemo, useState } from "react";
import ProtectedRoute from "../../../components/ProtectedRoute";
import { auth } from "../../../lib/firebase";
import type { CrmSalesIngestionV1 } from "../../../lib/agents/sales-01/crm-export";
import type { CrmFounderApproval, CrmIngestionPlan, CrmIngestionReceipt } from "../../../lib/agents/crm-01/types";

export default function CrmPhase1APage() {
  const [raw, setRaw] = useState(""); const [plan, setPlan] = useState<CrmIngestionPlan | null>(null); const [approved, setApproved] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [receipt, setReceipt] = useState<CrmIngestionReceipt | null>(null);
  const parsed = useMemo(() => { try { return raw.trim() ? JSON.parse(raw) as CrmSalesIngestionV1 : null; } catch { return null; } }, [raw]);
  async function token() { const user = auth.currentUser; if (!user) throw new Error("Admin session unavailable."); return { user, token: await user.getIdToken() }; }
  async function preview() { if (!parsed) return; setBusy(true); setMessage(""); setPlan(null); setReceipt(null); try { const session = await token(); const response = await fetch("/api/admin/agents/crm-01/preview", { method: "POST", headers: { Authorization: `Bearer ${session.token}`, "Content-Type": "application/json" }, body: JSON.stringify({ export: parsed, mappings: {} }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || body.code); setPlan(body.plan); } catch (error) { setMessage(error instanceof Error ? error.message : "Preview failed."); } finally { setBusy(false); } }
  async function ingest() { if (!parsed || !plan || !approved) return; setBusy(true); setMessage(""); try { const session = await token(); const approvedAt = new Date().toISOString(); const approval: CrmFounderApproval = { approved: true, scope: "crm_ingestion", approvedByUid: session.user.uid, approvedAt, artifactSha256: plan.artifactSha256, ingestionPlanSha256: plan.planSha256, expectedRevisions: plan.expectedRevisions, approvedMappings: plan.mappings, authority: { outreach: false, campaigns: false, payments: false, revenueInvocation: false, closerInvocation: false, externalAction: false } }; const response = await fetch("/api/admin/agents/crm-01/ingest", { method: "POST", headers: { Authorization: `Bearer ${session.token}`, "Content-Type": "application/json" }, body: JSON.stringify({ export: parsed, mappings: plan.mappings, plan, approval }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || body.code); setReceipt(body.receipt); } catch (error) { setMessage(error instanceof Error ? error.message : "Atomic ingestion failed."); } finally { setBusy(false); } }
  return <ProtectedRoute allowedRole="admin"><main className="min-h-screen bg-slate-950 px-4 py-10 text-white"><div className="mx-auto max-w-6xl space-y-6"><header><p className="text-sm font-semibold uppercase tracking-widest text-cyan-300">Admin-only · Founder-supervised</p><h1 className="text-3xl font-bold">CRM-01 Phase 1A</h1><p className="text-slate-300">Preview and approve one exact deterministic SALES export. Preview writes nothing. Approval authorizes only the displayed atomic CRM transaction—not outreach or downstream action.</p></header><section className="space-y-4 rounded-2xl border border-slate-700 bg-slate-900 p-5"><input type="file" accept=".json,application/json" onChange={(e) => void e.target.files?.[0]?.text().then((text) => { setRaw(text); setPlan(null); })} /><textarea value={raw} onChange={(e) => { setRaw(e.target.value); setPlan(null); }} className="min-h-64 w-full rounded-xl bg-slate-950 p-3 font-mono text-xs" placeholder="Paste crm-sales-ingestion-v1 JSON"/><button disabled={!parsed || busy} onClick={preview} className="rounded-xl bg-cyan-300 px-5 py-3 font-bold text-slate-950 disabled:opacity-50">{busy ? "Working…" : "Preview deterministic ingestion"}</button></section>{message && <p className="rounded-xl bg-red-950 p-4 text-red-200">{message}</p>}{plan && <section className="space-y-4 rounded-2xl border border-cyan-700 bg-cyan-950/20 p-5"><h2 className="text-xl font-bold">Exact ingestion plan</h2><div className="grid gap-2 text-sm sm:grid-cols-3"><p>Creates: {plan.creates.length}</p><p>Updates: {plan.updates.length}</p><p>Possible matches: {plan.possibleMatches.length}</p><p>Stage: {plan.stage}</p><p>DNC: {plan.dncEvaluation}</p><p>Plan: {plan.planSha256.slice(0, 16)}…</p></div><details><summary>Review complete plan, revisions, mappings, history and unknowns</summary><pre className="mt-3 max-h-[40rem] overflow-auto rounded-xl bg-slate-950 p-4 text-xs">{JSON.stringify(plan, null, 2)}</pre></details><label className="flex gap-3 rounded-xl border border-amber-600 p-4"><input type="checkbox" checked={approved} onChange={(e) => setApproved(e.target.checked)}/><span>I approve this exact artifact, plan, expected revisions and mappings for CRM ingestion only. No outreach, campaigns, payments, REVENUE, CLOSER, or external action.</span></label><button disabled={!approved || busy} onClick={ingest} className="rounded-xl bg-emerald-300 px-5 py-3 font-bold text-slate-950 disabled:opacity-50">Commit exact atomic CRM ingestion</button></section>}{receipt && <section className="rounded-2xl border border-emerald-700 bg-emerald-950/20 p-5"><h2 className="text-xl font-bold">CRM ingestion complete</h2><pre className="mt-3 overflow-auto text-xs">{JSON.stringify(receipt, null, 2)}</pre><p className="mt-3 text-sm">No outreach or downstream action was authorized.</p></section>}</div></main></ProtectedRoute>;
}
