"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import ProtectedRoute from "../../../../../components/ProtectedRoute";
import { auth } from "../../../../../lib/firebase";
import type { CrmAccountDetailReadModel } from "../../../../../lib/agents/crm-01/read-types";
import MutationPanel from "./MutationPanel";

async function fetchDetail(accountId: string): Promise<CrmAccountDetailReadModel> {
  const user = auth.currentUser;
  if (!user) throw new Error("Admin session unavailable.");
  const response = await fetch(`/api/admin/agents/crm-01/accounts/${encodeURIComponent(accountId)}`, { headers: { Authorization: `Bearer ${await user.getIdToken()}` }, cache: "no-store" });
  const body = await response.json();
  if (!response.ok) throw new Error(body.error || body.code || "Account detail failed.");
  return body;
}
const unknown = (value: string | number | null | undefined) => value ?? "Unknown";

export default function CrmAccountControlRoomPage() {
  const params = useParams<{ accountId: string }>(); const accountId = decodeURIComponent(params.accountId);
  const [data, setData] = useState<CrmAccountDetailReadModel | null>(null); const [error, setError] = useState("");
  const reload = () => { setError(""); void fetchDetail(accountId).then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : "Account detail failed.")); };
  useEffect(() => { reload(); }, [accountId]);
  return <ProtectedRoute allowedRole="admin"><main className="min-h-screen bg-slate-950 px-4 py-10 text-white"><div className="mx-auto max-w-7xl space-y-6"><header><Link href="/admin/crm-01/accounts" className="text-cyan-300">← Accounts</Link><h1 className="mt-3 text-3xl font-bold">{data?.account.displayName ?? "Account Control Room"}</h1><p className="text-slate-300">Read-only current projection, immutable inputs and audit history. Stored inference remains labeled as inference.</p></header>
    {error && <p className="rounded-xl border border-red-700 bg-red-950 p-4 text-red-200">{error}</p>}{!data && !error && <p>Loading canonical relationship…</p>}{data && <><section className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-900 p-5"><p className="text-xs uppercase text-slate-400">Relationship</p><p className="mt-1 font-bold">{unknown(data.account.relationshipStatus)}</p></div><div className="rounded-2xl bg-slate-900 p-5"><p className="text-xs uppercase text-slate-400">DNC</p><p className="mt-1 font-bold">{data.account.dnc.state} / {data.account.dnc.evaluation}</p></div><div className="rounded-2xl bg-slate-900 p-5"><p className="text-xs uppercase text-slate-400">Revision</p><p className="mt-1 font-bold">{unknown(data.account.revision)}</p></div></section>
      <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-xl font-bold">Contacts</h2><div className="mt-4 space-y-4">{data.contacts.length === 0 ? <p className="text-slate-400">No Contacts recorded.</p> : data.contacts.map((contact) => <article key={contact.id} className="rounded-xl bg-slate-950 p-4"><p className="font-semibold">{contact.name ?? "Name unknown"} · {contact.currentTitle ?? "Title unknown"}</p><p className="mt-1 text-sm">Function: {contact.stakeholderFunction ?? "Unknown"} · Problem ownership: {contact.problemOwnership ?? "Unknown"}</p><p className="text-sm">SALES inference — functional relevance: {contact.functionalRelevance ?? "Unavailable"}</p><p className="text-sm">Confidence: {contact.confidence ?? "Unknown"} · Freshness: {contact.freshness ?? "Unknown"}</p><p className="mt-1 text-sm">Route: {contact.contactRoute.type}{contact.contactRoute.value ? ` — ${contact.contactRoute.value}` : " — Unknown"}</p><p className="text-sm">Buying authority: {contact.buyingAuthority}</p>{contact.recommendedAsBestFirstContact ? <p className="mt-2 text-sm text-violet-200">SALES inference: Best First Contact — {contact.strategicRoleRationale}</p> : <p className="mt-2 text-sm text-amber-300">Best First Contact: unavailable/unknown. CRM made no recommendation.</p>}<p className="mt-2 text-xs text-slate-500">Identity evidence: {contact.identityEvidenceIds.join(", ") || "Unknown"} · Role evidence: {contact.currentRoleEvidenceIds.join(", ") || "Unknown"}</p><p className="text-xs text-slate-500">Route evidence: {contact.contactRoute.evidenceIds.join(", ") || "Unknown"} · Buying-authority evidence: {contact.buyingAuthorityEvidenceIds.join(", ") || "Unknown"}</p>{contact.conflictingEvidenceIds.length > 0 && <p className="text-xs text-amber-300">Conflicting role evidence: {contact.conflictingEvidenceIds.join(", ")}</p>}<p className="mt-1 text-xs text-slate-500">Provenance: {contact.provenance.join(", ") || "Unknown"}</p></article>)}</div></section>
      <section className="rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-xl font-bold">GROWTH qualification</h2><div className="mt-4 space-y-4">{data.growthOpportunities.length === 0 ? <p className="text-slate-400">No immutable GROWTH opportunity recorded.</p> : data.growthOpportunities.map((item) => <article key={item.id} className="rounded-xl bg-slate-950 p-4"><p className="font-semibold">{item.brand ?? "Brand unknown"} — {item.productOrEvent ?? "Product unknown"}</p><p className="text-sm">Score: {unknown(item.score)} · Band: {unknown(item.band)} · Confidence: {unknown(item.confidence)}</p><p className="mt-2 text-sm">Wedge: {item.wedge ?? "Unknown"}</p><p className="mt-2 text-xs text-slate-500">Immutable source entity · Provenance: {item.provenance.join(", ") || "Unknown"}</p></article>)}</div></section></div>
      <section className="rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-xl font-bold">Pursuits and approved/manual next actions</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{data.pursuits.length === 0 ? <p className="text-slate-400">No pursuit recorded.</p> : data.pursuits.map((item) => <article key={item.id} className="rounded-xl bg-slate-950 p-4"><p className="font-semibold">{item.stage ?? "Stage unknown"} · {item.disposition ?? "Disposition unknown"}</p><p className="text-sm">SALES decision: {item.salesPursuitDecision ?? "Unknown"}</p><p className="text-sm">Best First Contact: {item.contactSelection.status === "recommended" ? `SALES inference (${item.contactSelection.bestFirstContactId ?? "ID unavailable"})` : item.contactSelection.unavailableReason ?? "Unavailable/unknown; CRM made no selection."}</p><p className="mt-2 text-sm">Next action: {item.nextAction.description ?? "Unknown"}</p><p className="text-xs text-amber-300">Execution authorized: No</p><p className="mt-2 text-sm">Rights: {item.rights.status ?? "Unknown"}{item.rights.conditionalRequirement ? ` — ${item.rights.conditionalRequirement}` : ""}</p><p className="text-sm">Retailer independence: {item.retailerIndependence.posture ?? "Unknown"}</p>{item.unknowns.map((entry) => <p key={entry.text} className="mt-1 text-xs text-violet-200">Unknown: {entry.text} ({entry.status ?? "unresolved"})</p>)}</article>)}</div></section>
      <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-amber-700 bg-amber-950/20 p-5"><h2 className="text-xl font-bold">Attention Items</h2><div className="mt-4 space-y-3">{data.attentionItems.length === 0 ? <p className="text-slate-400">No Attention Items recorded.</p> : data.attentionItems.map((item) => <article key={item.id} className="rounded-xl bg-slate-950 p-4"><p className="font-semibold">{item.reason ?? "Reason unknown"}</p><p className="text-sm">{item.type} · {item.priority} · {item.status} · Due/review: {item.dueAt ?? "Unknown"}</p></article>)}</div></section>
      <section className="rounded-2xl border border-emerald-700 bg-emerald-950/20 p-5"><h2 className="text-xl font-bold">Commercial truth</h2>{data.commercial.length === 0 ? <p className="mt-4 text-slate-400">No commercial milestone evidence recorded.</p> : data.commercial.map((item, index) => <article key={index} className="mt-4 rounded-xl bg-slate-950 p-4"><p>Free First: {item.freeFirst.state ?? "Unknown"} · Revenue $0 · Live {String(item.freeFirst.live)} · Scan verified {String(item.freeFirst.scanVerified)}</p><p>Product 2: {item.product2.state ?? "Unknown"} · Amount {item.product2.amountUsd ?? "Unknown"} · Payment ref {item.product2.paymentReference ?? "Unknown"}</p><p>Creator Network: {item.creatorNetwork.state ?? "Unknown"} · Amount {item.creatorNetwork.amountUsd ?? "Unknown"}</p><p className="mt-2 text-xs text-slate-400">Hypothesis/opportunity, proposed, expected, committed, collected and reversed remain distinct.</p></article>)}</section></div>
      <MutationPanel data={data} onCommitted={reload}/><section className="rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-xl font-bold">Canonical history and provenance</h2><div className="mt-4 space-y-3">{data.timeline.length === 0 ? <p className="text-slate-400">No history recorded.</p> : data.timeline.map((item) => <article key={`${item.entityType}-${item.id}`} className="border-l-2 border-cyan-500 pl-4"><p className="font-semibold">{item.title}</p><p className="text-sm text-slate-300">{item.summary ?? "Summary unavailable"}</p><p className="text-xs text-slate-500">{item.effectiveAt ?? "Effective date unknown"} · {item.classification ?? "Classification unknown"} · Provenance: {item.provenance.join(", ") || "Unknown"}</p>{item.correctionOf && <p className="text-xs text-amber-300">Correction of: {item.correctionOf}</p>}{item.supersededBy && <p className="text-xs text-amber-300">Superseded by: {item.supersededBy}</p>}</article>)}</div></section>
      {data.truncationWarnings.map((item) => <p key={item} className="rounded-xl border border-amber-700 bg-amber-950 p-4 text-amber-200">{item}</p>)}</>}
  </div></main></ProtectedRoute>;
}
