import assert from "node:assert/strict";
import test from "node:test";
import { APPROVED_CRM_CONVERSATION_CONTRACT_SHA256, CRM_CONVERSATION_CANONICALIZATION, CRM_CONVERSATION_CONTRACT_SHA256, CRM_CONVERSATION_SCHEMA, CRM_CONVERSATION_VERSION, canonicalConversationId } from "../../lib/agents/crm-01/conversation.ts";
import { buildCrmMutationPlan, crmRecordPath } from "../../lib/agents/crm-01/mutation-planner.ts";
import { constructMutationPacket, validateMutationClientRequest } from "../../lib/agents/crm-01/mutation-validation.ts";

const CRM_SHA="68129fc2d2d4fdd5646b93879d0b469a71c3ef4c93e84fd0e4aaccc011fa8194",AT="2026-09-29T12:00:00.000Z";
const rec=(entityType,id,data,revision=1)=>({recordSchemaVersion:"crm-record-v1",id,entityType,revision,createdAt:AT,updatedAt:AT,data,provenance:["founder_provided_information"],history:[]});
const ev=(classification="future_brand_statement")=>[{id:"ev1",classification,source:"Exact communication artifact",statement:"Verified participants and channel",observedAt:AT,evidenceUrl:null}];
const context=(provider="gmail")=>({participants:[{type:"crm_contact",id:"contact"},{type:"goshsha_internal",id:"goshsha_founder"}],senderParticipantKey:"crm_contact:contact",recipientParticipantKeys:["goshsha_internal:goshsha_founder"],channel:"email",replyToInteractionId:null,providerReference:{provider,externalMessageId:"msg-1",externalThreadId:"thread-1",externalConversationId:null,evidenceIds:["ev1"]},evidenceIds:["ev1"]});
function fixture(){const account=crmRecordPath("account","acct"),pursuit=crmRecordPath("salesPursuit","pursuit"),contact=crmRecordPath("contact","contact");return{records:{[account]:rec("account","acct",{displayName:"Brand"}),[pursuit]:rec("salesPursuit","pursuit",{accountId:"acct",contactIds:["contact"],stage:"Engaged"}),[contact]:rec("contact","contact",{accountId:"acct",name:"Person"})},revisions:{[account]:1,[pursuit]:1,[contact]:1}};}
function plan({conversation=context(),contactId="contact",records,revisions,key="mutation_1"}={}){const base=fixture(),request=validateMutationClientRequest({idempotencyKey:key,expectedRevisions:revisions??base.revisions,mutation:{kind:"record_interaction",accountId:"acct",pursuitId:"pursuit",contactId,interactionType:"inbound_received",exactStatement:"Interesting, show me more.",summary:"Brand replied.",occurredAt:AT,conversation,evidence:ev()}}),packet=constructMutationPacket(request,"founder",AT);return{packet,plan:buildCrmMutationPlan({packet,records:records??base.records,crmContractSha256:CRM_SHA})};}

test("conversation identity is deterministic, provider independent and versioned",()=>{const a=plan(),b=plan({conversation:context("linkedin"),key:"mutation_2"});const ap=a.plan.operations.find(x=>x.entityType==="salesPursuit").after.data.canonicalConversation,bp=b.plan.operations.find(x=>x.entityType==="salesPursuit").after.data.canonicalConversation;assert.equal(ap.conversationId,canonicalConversationId("acct","pursuit"));assert.equal(ap.conversationId,bp.conversationId);assert.equal(ap.schemaVersion,CRM_CONVERSATION_SCHEMA);assert.equal(ap.version,CRM_CONVERSATION_VERSION);assert.equal(ap.canonicalizationVersion,CRM_CONVERSATION_CANONICALIZATION);assert.equal(CRM_CONVERSATION_CONTRACT_SHA256,APPROVED_CRM_CONVERSATION_CONTRACT_SHA256);assert.notEqual(ap.revisionSha256,bp.revisionSha256);assert.equal(ap.communicationAuthority,false);});
test("supervised interaction atomically binds participants, sender, recipients, factual channel and provider evidence",()=>{const result=plan().plan,interaction=result.operations.find(x=>x.entityType==="interaction").after,pursuit=result.operations.find(x=>x.entityType==="salesPursuit").after,conversation=pursuit.data.canonicalConversation;assert.equal(result.operations.length,2);assert.equal(interaction.data.conversationId,conversation.conversationId);assert.equal(interaction.data.senderParticipantKey,"crm_contact:contact");assert.deepEqual(interaction.data.recipientParticipantKeys,["goshsha_internal:goshsha_founder"]);assert.equal(interaction.data.channel,"email");assert.equal(interaction.data.providerReference.externalThreadId,"thread-1");assert.deepEqual(conversation.interactionReferences.map(x=>x.interactionId),[interaction.id]);assert.equal(interaction.data.communicationAuthority,false);assert.equal(interaction.data.executionAuthorized,false);});
test("unknown continuity remains unknown and historical interactions remain valid",()=>{const result=plan({conversation:null}).plan;assert.equal(result.operations.length,1);const interaction=result.operations[0].after;assert.equal(interaction.data.conversationId,null);assert.equal(interaction.data.senderParticipantKey,null);assert.deepEqual(interaction.data.recipientParticipantKeys,[]);assert.equal(interaction.data.channel,null);});
test("unrelated contacts, unsupported participants and SALES inference fail closed",()=>{const base=fixture(),contact=crmRecordPath("contact","contact");base.records[contact]=rec("contact","contact",{accountId:"other"});assert.throws(()=>plan({records:base.records,revisions:base.revisions}),/does not belong/);assert.throws(()=>validateMutationClientRequest({idempotencyKey:"mutation_1",expectedRevisions:fixture().revisions,mutation:{kind:"record_interaction",accountId:"acct",pursuitId:"pursuit",contactId:"contact",interactionType:"manual_note",exactStatement:null,summary:"Recommendation only",occurredAt:AT,conversation:context(),evidence:ev("sales_strategic_inference")}}),/cannot establish conversation facts/);const bad=context();bad.senderParticipantKey="crm_contact:other";assert.throws(()=>plan({conversation:bad}),/explicit canonical participants/);});
test("reply continuity is revision-bound, ordered and cannot cross conversations",()=>{const first=plan(),pursuitOp=first.plan.operations.find(x=>x.entityType==="salesPursuit"),interactionOp=first.plan.operations.find(x=>x.entityType==="interaction"),base=fixture(),pursuitPath=crmRecordPath("salesPursuit","pursuit"),interactionPath=crmRecordPath("interaction",interactionOp.after.id);base.records[pursuitPath]=pursuitOp.after;base.records[interactionPath]=interactionOp.after;base.revisions[pursuitPath]=2;base.revisions[interactionPath]=1;const next=context();next.replyToInteractionId=interactionOp.after.id;next.providerReference=null;const second=plan({conversation:next,records:base.records,revisions:base.revisions,key:"mutation_2"}).plan,interaction=second.operations.find(x=>x.entityType==="interaction").after,conversation=second.operations.find(x=>x.entityType==="salesPursuit").after.data.canonicalConversation;assert.equal(interaction.data.inReplyToInteractionId,interactionOp.after.id);assert.equal(conversation.revision,2);assert.deepEqual(conversation.interactionReferences.map(x=>x.interactionId),[interactionOp.after.id,interaction.id]);const stale={...base.revisions,[pursuitPath]:1};assert.throws(()=>plan({conversation:next,records:base.records,revisions:stale,key:"mutation_3"}),/Expected revision is missing or stale/);});
