import assert from "node:assert/strict";
import test from "node:test";
import { buildCrmRevenueSnapshot, CrmRevenueSnapshotError } from "../../lib/agents/crm-01/revenue-snapshot.ts";

const CRM_SHA="68129fc2d2d4fdd5646b93879d0b469a71c3ef4c93e84fd0e4aaccc011fa8194",at="2026-09-27T12:00:00.000Z";
function rec(entityType,id,data={},revision=1,provenance=[]){return{recordSchemaVersion:"crm-record-v1",id,entityType,revision,createdAt:at,updatedAt:at,data,provenance,history:[]};}
function records({legacy=false,dnc="unknown"}={}){const salesSource=legacy?undefined:{acceptedSalesArtifactSha256:"artifact",playbookSchemaVersion:"sales-playbook-v1",salesContractVersion:"V1.2",salesContractSha256:"sales-contract",providerProjectionVersion:"sales-01-provider-intelligence-v1.1",providerProjectionSha256:"projection"};return[
  rec("account","acct",{displayName:"Brand",dnc,dncEvaluation:dnc==="active"?"blocked":"review_required"},1,["sales_public_evidence"]),
  rec("growthOpportunity","growth",{accountId:"acct",candidateSnapshot:{candidateSha256:"candidate",completeCandidate:{brand:"Brand",computed:{finalScore:81,band:"Immediate Priority"}}},qualificationSnapshot:{score:81,band:"Immediate Priority",confidence:"High",founderStagePursuitFeasibility:"High"},sourceEnvelopeId:"env",sourceEnvelopeSha256:"growth-sha",immutable:true},1,["growth_derived_evidence"]),
  rec("salesPursuit","pursuit",{accountId:"acct",opportunityId:"growth",contactIds:["contact"],stage:"Engaged",disposition:"Active",salesPursuitDecision:"Pursue Now",selectedEntryOfferId:"Free First",salesSource,unknowns:[{originalText:"Rights unknown",status:"unresolved",salesEvidenceIds:[]}],rights:{status:"unknown",conditionalRequirement:"Brand must confirm rights."},retailerIndependence:{posture:"retailer_independent",description:"No retailer dependency."},nextAction:{actionId:"next",description:"Founder review",owner:"Founder",status:"open",dueAt:null,timingBasis:null,approvalRequired:true,executionAuthorized:false,sourceEvidenceIds:[]}},2,["sales_strategic_inference","unknown"]),
  rec("contact","contact",{accountId:"acct",currentTitle:"VP Brand",strategicRoles:["Best First Contact"],functionalRelevanceClassification:"sales_inference",buyingAuthority:"unknown",buyingAuthorityEvidenceIds:[],freshness:"current",conflictingEvidenceIds:[],dnc:"unknown",dncEvaluation:"review_required"},1,["sales_public_evidence","sales_strategic_inference"]),
  rec("interaction","interaction",{accountId:"acct",pursuitId:"pursuit",contactId:"contact",type:"inbound_received",exactStatement:"Interesting, show me more.",summary:"Brand expressed interest.",occurredAt:at,evidence:[{id:"ev-brand",classification:"future_brand_statement",source:"Brand reply",statement:"Interesting, show me more.",observedAt:at,evidenceUrl:null}]},1,["future_brand_statement"]),
  rec("decision","decision",{accountId:"acct",pursuitId:"pursuit",type:"founder_review",decision:"Continue review",effectiveAt:at,evidence:[],doesNotAuthorizeExternalAction:true},1,["founder_provided_information"]),
  rec("milestone","milestone",{accountId:"acct",pursuitId:"pursuit",type:"free_first_accepted",summary:"Accepted",occurredAt:at,evidence:[{id:"ev-accept",classification:"future_brand_statement",source:"Brand reply",statement:"We will try it.",observedAt:at,evidenceUrl:null}],freeFirstRevenueUsd:0,paymentVerified:false},1,["future_brand_statement"]),
  rec("attentionItem","attention",{accountId:"acct",pursuitId:"pursuit",type:"condition_alert",reason:"Proof required",priority:"high",status:"open",dueAt:null,triggeringCondition:"scan_unverified",evidence:[]},1,["system_generated_state"]),
];}
function build(options={}){return buildCrmRevenueSnapshot({accountId:"acct",pursuitId:"pursuit",records:records(options),truncatedCollections:[],generatedAt:at,generatedByUid:"founder",crmContractVersion:"V1.1",crmContractSha256:CRM_SHA});}

test("snapshot is deterministic, revision-bound, provenance-preserving and nonauthorizing",()=>{const a=build(),b=build();assert.deepEqual(a,b);assert.equal(a.snapshot.revisionBinding.records.map(x=>x.recordPath).join("\n"),[...a.snapshot.revisionBinding.records].sort((x,y)=>x.recordPath.localeCompare(y.recordPath)).map(x=>x.recordPath).join("\n"));assert.equal(a.snapshot.interactions[0].classification,"attributed_statement");assert.equal(a.snapshot.interactions[0].exactAttributedStatement,"Interesting, show me more.");assert.equal(a.snapshot.founderDecisions[0].doesNotAuthorizeExternalAction,true);assert.deepEqual(new Set(Object.values(a.snapshot.authority)),new Set([false]));});
test("Free First is always zero and nonrevenue while unsupported commercial truth stays unknown",()=>{const s=build().snapshot;assert.equal(s.commercialEvidence.freeFirst.priceUsd,0);assert.equal(s.commercialEvidence.freeFirst.revenueEligible,false);assert.equal(s.commercialEvidence.freeFirst.acceptance,"supported");assert.equal(s.commercialEvidence.paymentReferences.availability,"unavailable");assert.equal(s.commercialEvidence.refundReversalState,"unknown");for(const prohibited of ["revenuePriority","expectedRevenue","closestDollar","revenueVelocity","revenueEffort","monetizeNow","recommendedRevenueObjective"])assert.equal(prohibited in s,false);});
test("legacy SALES identity stays unavailable and makes the snapshot explicitly incomplete",()=>{const s=build({legacy:true});assert.equal(s.outcome,"incomplete");assert.equal(s.snapshot.upstream.sales.salesArtifactSha256,null);assert.ok(s.snapshot.snapshotIdentity.incompletenessReasons.some(x=>x.includes("acceptedSalesArtifactSha256")));});
test("material record and truncation changes change identity and remain incomplete",()=>{const a=build();const changed=records();changed.find(x=>x.id==="pursuit").revision=3;changed.find(x=>x.id==="pursuit").data.stage="Conversation Active";const b=buildCrmRevenueSnapshot({accountId:"acct",pursuitId:"pursuit",records:changed,truncatedCollections:["interactions"],generatedAt:at,generatedByUid:"founder",crmContractVersion:"V1.1",crmContractSha256:CRM_SHA});assert.notEqual(a.snapshot.revisionBinding.revisionSetSha256,b.snapshot.revisionBinding.revisionSetSha256);assert.notEqual(a.snapshot.snapshotIdentity.snapshotSha256,b.snapshot.snapshotIdentity.snapshotSha256);assert.equal(b.outcome,"incomplete");assert.ok(b.snapshot.snapshotIdentity.incompletenessReasons.some(x=>x.includes("interactions")));});
test("missing or malformed revision metadata fails closed",()=>{const missing=records().filter(x=>x.entityType!=="salesPursuit");assert.throws(()=>buildCrmRevenueSnapshot({accountId:"acct",pursuitId:"pursuit",records:missing,truncatedCollections:[],generatedAt:at,generatedByUid:"founder",crmContractVersion:"V1.1",crmContractSha256:CRM_SHA}),CrmRevenueSnapshotError);const malformed=records();malformed[0].revision=0;assert.throws(()=>buildCrmRevenueSnapshot({accountId:"acct",pursuitId:"pursuit",records:malformed,truncatedCollections:[],generatedAt:at,generatedByUid:"founder",crmContractVersion:"V1.1",crmContractSha256:CRM_SHA}),/revision metadata/);});
test("active DNC blocks execution eligibility without granting downstream authority",()=>{const s=build({dnc:"active"}).snapshot;assert.equal(s.relationshipSafety.effectiveExecutionState,"blocked");assert.equal(s.authority.revenueInvocationAuthorized,false);});
