import { NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { adminDb, adminStorage } from "@/lib/firebase-admin";

export async function POST(req: Request) {
  try {
    const formData = await req.formData();

    const brandName = String(formData.get("brandName") || "").trim();
    const campaignTitle = String(formData.get("campaignTitle") || "").trim();
    const productName = String(formData.get("productName") || "").trim();
    const campaignContentUrl = String(formData.get("campaignContentUrl") || "").trim();
    const campaignBrief = String(formData.get("campaignBrief") || "").trim();
    const targetImage = formData.get("targetImage") as File | null;

    if (!brandName || !campaignTitle || !productName || !campaignContentUrl || !targetImage) {
      return NextResponse.json(
        { error: "Missing required campaign fields." },
        { status: 400 }
      );
    }

    const campaignRef = adminDb.collection("campaigns").doc();
    const campaignId = campaignRef.id;

    const bytes = await targetImage.arrayBuffer();
    const buffer = Buffer.from(bytes);

    const bucket = adminStorage.bucket();
    const filePath = `brand-ar-targets/${campaignId}/${targetImage.name}`;
    const file = bucket.file(filePath);

    await file.save(buffer, {
      metadata: {
        contentType: targetImage.type || "image/jpeg",
      },
    });

    await file.makePublic();

    const arTargetImageUrl = `https://storage.googleapis.com/${bucket.name}/${filePath}`;

    await campaignRef.set({
      brandName,
      campaignTitle,
      productName,
      campaignBrief,
      campaignContentUrl,
      arTargetImageUrl,

      status: "live_preview",
      isFirstFreeIRLLaunch: true,
      isAutoGeneratedLaunch: true,

      arStatus: "ready",
      fundingStatus: "not_funded",
      brandApprovalStatus: "pending",
      payoutStatus: "not_ready",

      createdAt: FieldValue.serverTimestamp(),
      updatedAt: FieldValue.serverTimestamp(),
    });

    return NextResponse.json({
      success: true,
      campaignId,
    });
  } catch (error: any) {
    console.error("Launch first campaign error:", error);

    return NextResponse.json(
      { error: error.message || "Failed to launch first campaign." },
      { status: 500 }
    );
  }
}