import { NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { adminDb, adminStorage } from "../../../../lib/firebase-admin";

export async function POST(req: Request) {
  try {
    const formData = await req.formData();

    const campaignContentUrl = String(formData.get("campaignContentUrl") || "").trim();
    const campaignTitle = String(formData.get("campaignTitle") || "").trim();
    const productName = String(formData.get("productName") || "").trim();
    const brandName = String(formData.get("brandName") || "").trim();
    const brandId = String(formData.get("brandId") || "").trim();

    const fileObj = formData.get("targetImage");

    // ✅ Strong validation
    if (!campaignContentUrl) {
      return NextResponse.json(
        { error: "Missing campaign content URL." },
        { status: 400 }
      );
    }

    if (!fileObj || typeof fileObj === "string") {
      return NextResponse.json(
        { error: "Missing or invalid image file." },
        { status: 400 }
      );
    }

    const targetImage = fileObj as Blob;

    const campaignRef = adminDb.collection("campaigns").doc();
    const campaignId = campaignRef.id;

    // ✅ Convert safely
    const buffer = Buffer.from(await targetImage.arrayBuffer());

    const bucket = adminStorage.bucket();

    const filePath = `brand-ar-targets/${campaignId}/target.jpg`;
    const file = bucket.file(filePath);

    await file.save(buffer, {
      metadata: {
        contentType: "image/jpeg",
      },
      public: true, // 🔥 replaces makePublic()
    });

    // ✅ Correct public URL
    const arTargetImageUrl = `https://storage.googleapis.com/${bucket.name}/${filePath}`;

    await campaignRef.set({
      brandId: brandId || null,

      brandName: brandName || "Brand",
      campaignTitle: campaignTitle || "My First IRL Campaign",
      productName: productName || "My Product",

      campaignContentUrl,
      arTargetImageUrl,

      status: "live_preview",
      isFirstFreeIRLLaunch: true,
      isAutoGeneratedLaunch: true,

      arStatus: "ready",
      fundingStatus: "not_funded",
      brandApprovalStatus: "pending",
      payoutStatus: "not_ready",

      createdAt: FieldValue.serverTimestamp(),
      updatedAt: FieldValue.serverTimestamp(),
    });

    return NextResponse.json({
      success: true,
      campaignId,
    });
  } catch (error: any) {
    console.error("Launch first campaign error:", error);

    return NextResponse.json(
      { error: error.message || "Failed to launch first campaign." },
      { status: 500 }
    );
  }
}