import { NextResponse } from "next/server";
import { FieldValue } from "firebase-admin/firestore";
import { adminDb, adminStorage } from "../../../../lib/firebase-admin";
import { sendEmail } from "../../../../lib/postmark";

export async function POST(req: Request) {
  try {
    const formData = await req.formData();

    const campaignContentUrl = String(
      formData.get("campaignContentUrl") || ""
    ).trim();

    const campaignTitle = String(
      formData.get("campaignTitle") || ""
    ).trim();

    const productName = String(formData.get("productName") || "").trim();
    const brandName = String(formData.get("brandName") || "").trim();
    const brandId = String(formData.get("brandId") || "").trim();

    const fileObj = formData.get("targetImage");

    if (!campaignContentUrl) {
      return NextResponse.json(
        { error: "Missing campaign content URL." },
        { status: 400 }
      );
    }

    if (!fileObj || typeof fileObj === "string") {
      return NextResponse.json(
        { error: "Missing or invalid image file." },
        { status: 400 }
      );
    }

    const targetImage = fileObj as Blob;

    const campaignRef = adminDb.collection("campaigns").doc();
    const campaignId = campaignRef.id;

    const buffer = Buffer.from(await targetImage.arrayBuffer());

    const bucket = adminStorage.bucket();
    const filePath = `brand-ar-targets/${campaignId}/target.jpg`;
    const file = bucket.file(filePath);

    await file.save(buffer, {
      metadata: {
        contentType: "image/jpeg",
      },
    });

    const [arTargetImageUrl] = await file.getSignedUrl({
      action: "read",
      expires: "01-01-2035",
    });

    const finalBrandName = brandName || "Brand";
    const finalCampaignTitle = campaignTitle || "My First IRL Campaign";
    const finalProductName = productName || "My Product";

    await campaignRef.set({
      brandId: brandId || null,
      brandName: finalBrandName,
      campaignTitle: finalCampaignTitle,
      productName: finalProductName,

      campaignContentUrl,
      arTargetImageUrl,

      campaignType: "brand_first_irl_preview",
      status: "live_preview",
      isFirstFreeIRLLaunch: true,
      isAutoGeneratedLaunch: true,

      arStatus: "needs_admin_review",
      fundingStatus: "not_funded",
      brandApprovalStatus: "pending",
      payoutStatus: "not_ready",

      createdAt: FieldValue.serverTimestamp(),
      updatedAt: FieldValue.serverTimestamp(),
    });

    await adminDb.collection("notifications").add({
      userId: "admin",
      role: "admin",
      type: "new_first_irl_campaign",
      title: "New IRL Campaign Needs AR",
      message: `${finalBrandName} launched their first IRL campaign: ${finalCampaignTitle}`,
      campaignId,
      isRead: false,
      createdAt: FieldValue.serverTimestamp(),
      updatedAt: FieldValue.serverTimestamp(),
    });

    const appUrl =
      process.env.NEXT_PUBLIC_APP_URL || "https://irl.goshsha.com";

    await sendEmail({
      to: process.env.ADMIN_EMAIL || "athena@goshsha.com",
      subject: "New IRL Campaign Needs AR",
      htmlBody: `
        <h2>New First IRL Campaign Needs AR</h2>
        <p><strong>Brand:</strong> ${finalBrandName}</p>
        <p><strong>Campaign:</strong> ${finalCampaignTitle}</p>
        <p><strong>Product:</strong> ${finalProductName}</p>
        <p><strong>Content URL:</strong> <a href="${campaignContentUrl}">${campaignContentUrl}</a></p>
        <p><strong>Target Image:</strong> <a href="${arTargetImageUrl}">View image</a></p>
        <p><a href="${appUrl}/admin/review">Open Admin Review</a></p>
      `,
      textBody: `
New First IRL Campaign Needs AR

Brand: ${finalBrandName}
Campaign: ${finalCampaignTitle}
Product: ${finalProductName}
Content URL: ${campaignContentUrl}
Target Image: ${arTargetImageUrl}

Open Admin Review:
${appUrl}/admin/review
      `.trim(),
    });

    return NextResponse.json({
      success: true,
      campaignId,
    });
  } catch (error: any) {
    console.error("Launch first campaign error:", error);

    return NextResponse.json(
      { error: error.message || "Failed to launch first campaign." },
      { status: 500 }
    );
  }
}