import { NextResponse } from "next/server";
import { adminAuth, adminDb } from "../../../../../../lib/firebase-admin";
import { authorizeCrmAdmin } from "../../../../../../lib/agents/crm-01/admin-auth";
import { loadCrmContractMetadata } from "../../../../../../lib/agents/crm-01/contract";
import { CrmRevenueSnapshotError } from "../../../../../../lib/agents/crm-01/revenue-snapshot";
import { getCrmRevenueSnapshot } from "../../../../../../lib/agents/crm-01/revenue-snapshot-service";
import { crmReadErrorResponse } from "../../../../../../lib/agents/crm-01/read-route";
import { buildApprovedActionPackage, RevenueApprovalError } from "../../../../../../lib/agents/revenue-01/approved-action";
import { COMMERCIAL_GOAL_SHA256 } from "../../../../../../lib/agents/revenue-01/commercial-goals";
import { loadRevenueContractMetadata, RevenueContractIntegrityError } from "../../../../../../lib/agents/revenue-01/contract";
import { createDeterministicRevenueRecommendation } from "../../../../../../lib/agents/revenue-01/service";
import type { RevenueObjectiveFamily, RevenueRunContext } from "../../../../../../lib/agents/revenue-01/types";
import { normalizeRevenueRunContext, RevenueValidationError } from "../../../../../../lib/agents/revenue-01/validation";

export const runtime="nodejs";export const dynamic="force-dynamic";
const MAX_REQUEST_BYTES=3_072,APPROVED_GOAL_SHA256="692a00c032d7ac1fea441b7d1bdf695fe2d6125e7a47bcd704fde0d17bb446d6";
const families:RevenueObjectiveFamily[]=["resolve_evidence_or_safety_blocker","establish_qualified_engagement","complete_proof_milestone","pursue_standard_paid_conversion","pursue_repeat_or_retention","pause_no_commercial_action"];
const headers={"Cache-Control":"no-store, max-age=0",Pragma:"no-cache"}as const,response=(body:unknown,status=200)=>NextResponse.json(body,{status,headers});
const id=(x:unknown):x is string=>typeof x==="string"&&/^[A-Za-z0-9_-]{1,128}$/.test(x),sha=(x:unknown):x is string=>typeof x==="string"&&/^[a-f0-9]{64}$/.test(x);
const exact=(x:Record<string,unknown>,keys:string[])=>Object.keys(x).length===keys.length&&keys.every(k=>Object.hasOwn(x,k));
function parse(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))throw new RevenueApprovalError("invalid_approval_request","Approval request must be an object.");const b=value as Record<string,unknown>,keys=["accountId","pursuitId","runContext","displayedRecommendationId","expectedRevisionSetSha256","selectedFamily","explicitFounderApproval"];if(!exact(b,keys)||!id(b.accountId)||!id(b.pursuitId)||!id(b.displayedRecommendationId)||!sha(b.expectedRevisionSetSha256)||!families.includes(b.selectedFamily as RevenueObjectiveFamily)||b.explicitFounderApproval!==true||!b.runContext||typeof b.runContext!=="object"||Array.isArray(b.runContext))throw new RevenueApprovalError("invalid_approval_request","Exact Account, Pursuit, recommendation intent, revision binding, selected family, Founder context and explicit approval are required.");const context=b.runContext as Record<string,unknown>;if(!exact(context,["reportingMonth","founderSuppliedCollectedBaseline","baselineEvidenceClassification"]))throw new RevenueApprovalError("invalid_approval_request","Founder context contains unsupported fields.");return{accountId:b.accountId,pursuitId:b.pursuitId,displayedRecommendationId:b.displayedRecommendationId,expectedRevisionSetSha256:b.expectedRevisionSetSha256,selectedFamily:b.selectedFamily as RevenueObjectiveFamily,runContext:normalizeRevenueRunContext(context as RevenueRunContext)};}

export async function POST(request:Request){try{const length=Number(request.headers.get("content-length")||"0");if(length>MAX_REQUEST_BYTES)return response({code:"request_too_large",error:"Approval request exceeds the approved size limit."},413);const admin=await authorizeCrmAdmin(request,{verifyIdToken:t=>adminAuth.verifyIdToken(t),loadUser:async uid=>{const user=await adminDb.collection("users").doc(uid).get();return{exists:user.exists,isAdmin:user.data()?.isAdmin===true};}});const raw=await request.text();if(Buffer.byteLength(raw,"utf8")>MAX_REQUEST_BYTES)return response({code:"request_too_large",error:"Approval request exceeds the approved size limit."},413);let decoded:unknown;try{decoded=JSON.parse(raw);}catch{return response({code:"invalid_json",error:"Approval request must be valid JSON."},400);}const input=parse(decoded),now=new Date();await loadRevenueContractMetadata(now);if(COMMERCIAL_GOAL_SHA256!==APPROVED_GOAL_SHA256)throw new RevenueValidationError("commercial_goal_mismatch","Commercial goal integrity check failed.");const crm=await loadCrmContractMetadata(now);const fresh=await getCrmRevenueSnapshot({db:adminDb,accountId:input.accountId,pursuitId:input.pursuitId,generatedAt:now.toISOString(),generatedByUid:admin.uid,crmContractVersion:crm.version,crmContractSha256:crm.sha256});if(fresh.snapshot.snapshotIdentity.accountId!==input.accountId||fresh.snapshot.snapshotIdentity.pursuitId!==input.pursuitId)throw new RevenueApprovalError("scope_mismatch","Fresh CRM snapshot scope does not match the approval request.");const recommendation=await createDeterministicRevenueRecommendation({snapshot:fresh.snapshot,runContext:input.runContext,now});const approvedActionPackage=buildApprovedActionPackage({recommendation,selectedFamily:input.selectedFamily,displayedRecommendationId:input.displayedRecommendationId,expectedRevisionSetSha256:input.expectedRevisionSetSha256,approvedByUid:admin.uid,approvedAt:now.toISOString()});return response({outcome:"approved_package_created",freshSnapshot:fresh.snapshot,approvedActionPackage,persisted:false,downstreamInvoked:false});}catch(error){if(error instanceof RevenueApprovalError||error instanceof RevenueValidationError)return response({code:error.code,error:error.message},409);if(error instanceof RevenueContractIntegrityError)return response({code:"contract_integrity_failed",error:error.message},500);if(error instanceof CrmRevenueSnapshotError)return response({code:error.code,error:error.message},error.code==="required_record_missing"?404:422);return crmReadErrorResponse(error);}}
