import type { CrmRevenueSnapshotV1 } from "../crm-01/revenue-snapshot-types";
import type { EligibilityRecord, RevenueAssessment, RevenueBlocker, RevenueObjectiveFamily, RevenuePrerequisite } from "./types";

const FAMILIES:RevenueObjectiveFamily[]=["resolve_evidence_or_safety_blocker","establish_qualified_engagement","complete_proof_milestone","pursue_standard_paid_conversion","pursue_repeat_or_retention","pause_no_commercial_action"];
const verifiedMilestone=(s:CrmRevenueSnapshotV1,...types:string[])=>s.commercialEvidence.milestones.some(x=>types.includes(x.type??"")&&(x.verification==="verified"||x.evidence.length>0));
const hasEngagement=(s:CrmRevenueSnapshotV1)=>s.interactions.some(x=>x.type==="inbound_received"&&Boolean(x.exactAttributedStatement||x.evidence.length));
const salesIdentityComplete=(s:CrmRevenueSnapshotV1)=>Boolean(s.upstream.sales.salesArtifactSha256&&s.upstream.sales.playbookSchemaVersion&&s.upstream.sales.salesContractVersion&&s.upstream.sales.salesContractSha256&&s.upstream.sales.providerProjectionVersion&&s.upstream.sales.providerProjectionSha256);
const hardIncomplete=(s:CrmRevenueSnapshotV1)=>s.snapshotIdentity.incompletenessReasons.some(x=>/Linked immutable GROWTH|Pursuit Contacts|SALES source identity|bounded snapshot read limit/i.test(x));

export function evaluateRevenueEligibility(s:CrmRevenueSnapshotV1): RevenueAssessment {
  const blockers:RevenueBlocker[]=[],prerequisites:RevenuePrerequisite[]=[];const unknowns=[...s.unknowns.filter(x=>x.status!=="resolved").map(x=>x.statement),...s.snapshotIdentity.incompletenessReasons];
  const accountBlocked=s.relationshipSafety.accountDnc.evaluation==="blocked"||s.relationshipSafety.effectiveExecutionState==="blocked";
  const dncReview=!accountBlocked&&(s.relationshipSafety.accountDnc.evaluation!=="allowed"||s.relationshipSafety.contactDnc.some(x=>x.evaluation!=="allowed"));
  const rights=(s.pursuit.rightsState.status??"unknown").toLowerCase();const rightsConflict=/conflict/.test(rights);const rightsReady=/supported|verified|confirmed|ready|not_required/.test(rights);
  const engagement=hasEngagement(s),accepted=s.commercialEvidence.freeFirst.acceptance==="supported",live=s.commercialEvidence.freeFirst.publication==="supported",scan=s.commercialEvidence.freeFirst.physicalScan==="supported";
  const paidReady=verifiedMilestone(s,"product_2_accepted","paid_conversion_ready","paid_offer_accepted","creator_network_paid_ready");
  const priorPaid=s.commercialEvidence.paymentReferences.availability!=="unavailable"&&verifiedMilestone(s,"payment_collected","paid_customer");
  const legacyOffer=!s.pursuit.selectedEntryOfferId;
  const proofPathStarted=accepted||live||scan||s.pursuit.selectedEntryOfferId==="free-first-irl-campaign";
  const requiredProofComplete=!proofPathStarted||(accepted&&rightsReady&&live&&scan);
  const paidConversionPrerequisitesResolved=!accountBlocked&&!dncReview&&!rightsConflict&&rightsReady&&!legacyOffer&&!hardIncomplete(s)&&salesIdentityComplete(s)&&requiredProofComplete;
  if(accountBlocked)blockers.push({code:"active_dnc",description:"Canonical DNC blocks commercial execution; REVENUE cannot route around it.",owner:"CRM-01",hard:true});
  if(dncReview)blockers.push({code:"dnc_review_required",description:"DNC state is unknown or requires canonical review.",owner:"CRM-01",hard:true});
  if(rightsConflict)blockers.push({code:"rights_conflict",description:"Content-rights evidence conflicts and requires canonical resolution.",owner:"CRM-01",hard:true});
  if(legacyOffer)blockers.push({code:"stable_offer_unknown",description:"A stable approved offer identity is unavailable.",owner:"CRM-01",hard:true});
  if(hardIncomplete(s))blockers.push({code:"material_snapshot_gap",description:"Material source identity or bounded-read evidence is unavailable.",owner:"CRM-01",hard:true});
  let proofState:RevenueAssessment["proofState"]="unknown";
  if(!engagement)proofState="not_engaged";else if(!accepted)proofState="free_first_not_accepted";else if(!rightsReady)proofState="rights_or_inputs_unresolved";else if(!live)proofState="accepted_ready_not_live";else if(!scan)proofState="live_scan_unverified";else if(paidReady)proofState="paid_progression_evidenced";else proofState="proof_verified_paid_readiness_unknown";
  if(proofState==="rights_or_inputs_unresolved")prerequisites.push({code:"rights_inputs_required",description:"Brand-owned or properly licensed content and required activation inputs must be evidenced.",evidenceRequired:["Canonical rights/readiness evidence"]});
  if(proofState==="accepted_ready_not_live")prerequisites.push({code:"publication_required",description:"The accepted Free First activation must be published/live.",evidenceRequired:["Verified publication/live milestone"]});
  if(proofState==="live_scan_unverified")prerequisites.push({code:"physical_proof_required",description:"An appropriate Brand stakeholder physical scan/proof experience must be verified.",evidenceRequired:["Authoritative physical-scan/proof milestone"]});
  if(proofState==="proof_verified_paid_readiness_unknown")prerequisites.push({code:"paid_readiness_evidence_required",description:"Proof does not itself establish readiness for Product 2 or another paid path.",evidenceRequired:["Explicit paid-use interest, accepted approved offer, or equivalent canonical evidence"]});
  const safetyIssue=accountBlocked||dncReview, evidenceIssue=rightsConflict||legacyOffer||hardIncomplete(s)||proofState==="rights_or_inputs_unresolved"||proofState==="proof_verified_paid_readiness_unknown";
  const rows:Record<RevenueObjectiveFamily,EligibilityRecord>={
    resolve_evidence_or_safety_blocker:{family:"resolve_evidence_or_safety_blocker",eligible:evidenceIssue||dncReview,reasons:evidenceIssue||dncReview?["Material evidence or safety state must be resolved before a stronger objective."]:["No material evidence/safety blocker requires resolution."],desiredOutcome:"Obtain authoritative evidence or canonical resolution for the blocking state.",assignmentType:"None",successCondition:"The blocking state is resolved in a fresh canonical CRM snapshot.",requiredEvidence:["Fresh CRM snapshot containing the authoritative resolution"]},
    establish_qualified_engagement:{family:"establish_qualified_engagement",eligible:!safetyIssue&&!hardIncomplete(s)&&salesIdentityComplete(s)&&s.upstream.sales.pursuitDecision==="Pursue Now"&&!engagement,reasons:[],desiredOutcome:"Establish qualified Brand engagement under the existing SALES playbook.",assignmentType:"Pursuit",successCondition:"A canonical CRM interaction records qualified Brand engagement.",requiredEvidence:["Exact Brand response or other canonical engagement evidence"]},
    complete_proof_milestone:{family:"complete_proof_milestone",eligible:!safetyIssue&&!hardIncomplete(s)&&engagement&&!paidReady&&["free_first_not_accepted","accepted_ready_not_live","live_scan_unverified"].includes(proofState),reasons:[],desiredOutcome:proofState==="free_first_not_accepted"?"Secure evidence-supported Free First acceptance.":proofState==="accepted_ready_not_live"?"Get the accepted, rights-ready Free First activation published/live.":proofState==="live_scan_unverified"?"Obtain verified physical scan/proof experience.":null,assignmentType:"Proof / Progression",successCondition:proofState==="free_first_not_accepted"?"Canonical CRM evidence records Free First acceptance.":proofState==="accepted_ready_not_live"?"Authoritative evidence records the activation as published/live.":"Authoritative evidence records the appropriate physical scan/proof experience.",requiredEvidence:proofState==="free_first_not_accepted"?["Exact Brand acceptance evidence"]:proofState==="accepted_ready_not_live"?["Verified publication/live reference"]:["Verified physical-scan/proof reference"]},
    pursue_standard_paid_conversion:{family:"pursue_standard_paid_conversion",eligible:paidConversionPrerequisitesResolved&&paidReady&&Boolean(s.pursuit.selectedEntryOfferId&&s.pursuit.selectedEntryOfferId!=="free-first-irl-campaign"),reasons:[],desiredOutcome:"Progress the evidenced approved paid offer toward collection without representing payment as complete.",assignmentType:"Conversion",successCondition:"Authoritative payment evidence confirms successful collection for the approved offer.",requiredEvidence:["Canonical paid-offer progression evidence","Authoritative successful payment reference"]},
    pursue_repeat_or_retention:{family:"pursue_repeat_or_retention",eligible:!safetyIssue&&priorPaid&&verifiedMilestone(s,"repeat_purchase_interest","renewal_interest","expansion_interest"),reasons:[],desiredOutcome:"Progress an evidenced repeat, expansion, renewal, or retention opportunity.",assignmentType:"Expansion / Retention",successCondition:"Authoritative evidence records the repeat or retained paid outcome.",requiredEvidence:["Authoritative prior paid state","Canonical repeat/retention evidence","Authoritative new payment evidence"]},
    pause_no_commercial_action:{family:"pause_no_commercial_action",eligible:accountBlocked,reasons:accountBlocked?["Active canonical DNC requires no commercial execution."]:["No active hard stop requires pause."],desiredOutcome:"Take no commercial action while the canonical stop remains active.",assignmentType:"None",successCondition:"A future authoritative CRM snapshot establishes that the stop is no longer active.",requiredEvidence:["Authoritative CRM/legal/compliance-supported DNC correction or resolution"]},
  };
  for(const family of FAMILIES){const row=rows[family];if(!row.reasons.length)row.reasons.push(row.eligible?"All deterministic eligibility requirements are supported.":family==="pursue_repeat_or_retention"?"Authoritative prior paid and repeat/retention evidence is unavailable.":family==="pursue_standard_paid_conversion"?"Paid readiness for a stable approved paid offer is unsupported.":family==="complete_proof_milestone"?"No currently eligible proof milestone is established.":family==="establish_qualified_engagement"?"Qualification, SALES identity/decision, safety, or no-engagement requirements are not all supported.":"Objective is not required by current evidence.");}
  const precedence:RevenueObjectiveFamily[]=accountBlocked?["pause_no_commercial_action"]:["resolve_evidence_or_safety_blocker","pursue_repeat_or_retention","pursue_standard_paid_conversion","complete_proof_milestone","establish_qualified_engagement","pause_no_commercial_action"];
  let primaryFamily=precedence.find(x=>rows[x].eligible)??"resolve_evidence_or_safety_blocker";
  if(!rows[primaryFamily].eligible){rows.resolve_evidence_or_safety_blocker={...rows.resolve_evidence_or_safety_blocker,eligible:true,reasons:["No stronger objective is safely supported; obtain missing economic-path evidence."],desiredOutcome:"Resolve the missing evidence needed to identify a supported economic objective."};primaryFamily="resolve_evidence_or_safety_blocker";}
  const alternatives=precedence.filter(x=>x!==primaryFamily&&rows[x].eligible).slice(0,2);
  const selected=s.pursuit.selectedEntryOfferId;const opportunityAmountUsd=selected==="irl-retail-media-product-2"?99:selected==="creator-network"?75:null;
  const revenueState:RevenueAssessment["revenueState"]=paidReady&&opportunityAmountUsd!==null?"opportunity":opportunityAmountUsd!==null?"hypothesis":"unknown";
  const proximity:RevenueAssessment["proximity"]=paidReady?"Near":engagement?"Developing":"Distant";
  const priority:RevenueAssessment["priority"]=accountBlocked?"Blocked":primaryFamily==="pursue_standard_paid_conversion"||primaryFamily==="pursue_repeat_or_retention"?"Now":primaryFamily==="complete_proof_milestone"?"Next":primaryFamily==="establish_qualified_engagement"?"Develop":primaryFamily==="resolve_evidence_or_safety_blocker"?"Blocked":"Monitor";
  const timing:RevenueAssessment["timing"]=accountBlocked?"Pause":primaryFamily==="pursue_standard_paid_conversion"||primaryFamily==="pursue_repeat_or_retention"?"Monetize Now":primaryFamily==="complete_proof_milestone"||primaryFamily==="establish_qualified_engagement"?"Complete Proof Milestone First":"Resolve Evidence First";
  return{eligibility:FAMILIES.map(x=>rows[x]),blockers,prerequisites,primaryFamily,alternatives,proofState,revenueState,collectionState:"unknown",opportunityAmountUsd,proximity,velocity:"Unknown",friction:"Unknown",priority,timing,executionState:accountBlocked?"blocked":dncReview?"review_required":"eligible_for_founder_review",economicDesirability:s.upstream.growth.score!==null&&s.upstream.sales.pursuitDecision==="Pursue Now"?true:null,unknowns:[...new Set(unknowns)]};
}
