import { revenueSha256, revenueStableId } from "./canonical";
import { evaluateRevenueEligibility } from "./eligibility";
import { RECOMMENDATION_ENGINE_VERSION, RECOMMENDATION_SCHEMA_VERSION, type RevenueEngineInput, type RevenueRecommendationV1 } from "./types";
import { validateRevenueEngineInput } from "./validation";

export function buildRevenueRecommendation(raw:RevenueEngineInput):RevenueRecommendationV1{
  const input=validateRevenueEngineInput(raw),s=input.snapshot,a=evaluateRevenueEligibility(s),primary=a.eligibility.find(x=>x.family===a.primaryFamily)!;
  const binding={accountId:s.snapshotIdentity.accountId,pursuitId:s.snapshotIdentity.pursuitId,crmSnapshotId:s.snapshotIdentity.snapshotId,crmSnapshotSha256:s.snapshotIdentity.snapshotSha256,crmRevisionSetSha256:s.revisionBinding.revisionSetSha256,crmContractVersion:s.crmContract.version,crmContractSha256:s.crmContract.sha256,offerCatalogVersion:s.offerCatalog.version,offerCatalogSha256:s.offerCatalog.sha256,commercialGoalId:input.commercialGoal.goalId,commercialGoalVersion:input.commercialGoal.version,commercialGoalSha256:input.commercialGoal.sha256,revenueContractVersion:input.revenueContract.version,revenueContractSha256:input.revenueContract.sha256,recommendationEngineVersion:RECOMMENDATION_ENGINE_VERSION,normalizedRunContext:input.runContext};
  const evidenceIds=[...new Set(s.provenance.evidence.map(x=>x.id))].sort();
  const seed={schemaVersion:RECOMMENDATION_SCHEMA_VERSION,binding,primary:a.primaryFamily,alternatives:a.alternatives,eligibility:a.eligibility,blockers:a.blockers,prerequisites:a.prerequisites};
  const recommendationId=revenueStableId("revrec",seed),recommendationSha256=revenueSha256(seed);
  const owner=primary.family==="resolve_evidence_or_safety_blocker"||primary.family==="pause_no_commercial_action"?"CRM-01":primary.family==="establish_qualified_engagement"?"SALES-01":primary.assignmentType==="None"?"Founder":"future CLOSER-01";
  const result:RevenueRecommendationV1={schemaVersion:RECOMMENDATION_SCHEMA_VERSION,identity:{recommendationId,recommendationSha256,generatedAt:input.generatedAt,status:"Proposed"},binding,observedState:{snapshotCompleteness:s.snapshotIdentity.completeness,growthScore:s.upstream.growth.score,growthBand:s.upstream.growth.band,salesPursuitDecision:s.upstream.sales.pursuitDecision,crmStage:s.pursuit.stage,selectedEntryOfferId:s.pursuit.selectedEntryOfferId,proofState:a.proofState,relationshipSafety:s.relationshipSafety,nextAction:s.nextAction,evidenceIds},deterministicAssessment:{eligibility:a.eligibility,blockers:a.blockers,prerequisites:a.prerequisites,dataLimitations:s.snapshotIdentity.incompletenessReasons},economics:{revenueState:a.revenueState,collectionState:a.collectionState,opportunityAmountUsd:a.opportunityAmountUsd,proximity:a.proximity,velocity:a.velocity,friction:a.friction,priority:a.priority,timing:a.timing,executionState:a.executionState,economicDesirability:a.economicDesirability},recommendation:{family:primary.family,desiredOutcome:primary.desiredOutcome??"Resolve the unsupported economic path.",assignmentType:primary.assignmentType,rationale:primary.reasons.join(" "),assumptions:[],unknowns:a.unknowns,successCondition:primary.successCondition??"A fresh canonical snapshot supports a stronger objective.",requiredSuccessEvidence:primary.requiredEvidence,owningAgent:owner},alternatives:a.alternatives.map(family=>({family,reasonNotPrimary:"Eligible under current evidence but lower in the explicit deterministic precedence."})),horizons:{nextDollar:{classification:a.primaryFamily==="pursue_standard_paid_conversion"||a.primaryFamily==="pursue_repeat_or_retention"?"supported":a.opportunityAmountUsd!==null?"conditional":a.primaryFamily==="establish_qualified_engagement"?"not_close":"unknown",rationale:a.timing},first1000Monthly:{targetUsd:1000,founderBaselineUsd:input.runContext.founderSuppliedCollectedBaseline,baselineEvidenceClassification:input.runContext.baselineEvidenceClassification,accountContributionClassification:a.opportunityAmountUsd!==null?"opportunity":s.upstream.growth.score!==null?"hypothesis":"unknown",doesNotEstablishAccountRevenue:true},repeatableRevenueEngine:{classification:a.primaryFamily==="pursue_repeat_or_retention"?"supported":s.commercialEvidence.paymentReferences.availability==="unavailable"?"unavailable":"unvalidated",rationale:"Repeatability requires authoritative prior paid and repeat/retention evidence."}},authority:{founderApprovalState:"Not Requested",executionAuthorized:false,closerInvocationAuthorized:false,crmMutationAuthorized:false,paymentActionAuthorized:false,externalActionAuthorized:false},freshness:{currentForExactSnapshotOnly:true,invalidatedByAnyBindingChange:true}};
  return result;
}
