import type { GrowthCandidateInput, GrowthRunRequest } from "./types";

const benchmarkEvidence = (id: string, supportedClaim: string) => ({
  id,
  publisher: "Founder-approved supervised benchmark",
  sourceUrl: `https://example.invalid/goshsha-benchmark/${id}`,
  sourceType: "founder_supplied_benchmark" as const,
  publicationDate: "2026-01-01",
  accessDate: "2026-09-14",
  supportedClaim,
  classification: "verified_fact" as const,
  reliability: "high" as const,
  syntheticBenchmark: true,
});

export const buffBenchmarkCandidate: GrowthCandidateInput = {
  id: "buff-the-buff-ritual",
  brand: "Buff Beauty",
  productOrEvent: "The Buff Ritual",
  opportunityType: "Timely Trigger",
  executiveSummary: "Founder-approved synthetic fixture for deterministic scoring regression.",
  trigger: "The supervised benchmark supplies a current product opportunity.",
  whyNow: "The fixture preserves the previously approved benchmark inputs.",
  retailRelevance: "Verified physical-retail relevance is supplied by the benchmark.",
  creatorActivity: "Active product and creator content is supplied by the benchmark.",
  shelfNeed: "The ritual benefits from education and demonstration at the product.",
  goshshaWedge: "Carry the product ritual from creator content into the physical product scan moment.",
  retailerAssessment: { posture: "retailer_independent" },
  currentFit: "Current Goshsha production capabilities support a product-level activation.",
  recommendedOffering: "Free First IRL Campaign",
  freeFirst: {
    recommendation: "Recommended",
    intendedLearningOrProofPoint: "Prove that an on-product scan can explain The Buff Ritual at the shopping moment.",
    paidConversionHypothesis: "Product 2",
    scoreContribution: 0,
  },
  fastestRevenuePath: "$99 IRL Retail Media activation",
  revenuePathRationale: "Free First is the acquisition step; a subsequent standard paid activation is the paid destination.",
  commercialHypothesis: "A successful proof experience may support a standard Product 2 conversation.",
  founderStagePursuitFeasibility: "High",
  feasibilityRationale: "The synthetic benchmark defines a plausible small current-capability experiment.",
  confidence: "High",
  nextAction: "Founder review for a possible SALES-01 handoff.",
  handoff: "SALES-01",
  knownUnknowns: ["Brand interest and content rights remain unknown until verified."],
  evidence: [
    benchmarkEvidence("buff-retail", "Buff has the benchmark's verified physical-retail relevance."),
    benchmarkEvidence("buff-content", "The Buff Ritual has active product/creator content and shelf education need."),
    benchmarkEvidence("buff-trigger", "The opportunity has the benchmark's current trigger."),
  ],
  claims: [
    { id: "retail", claim: "Verified physical-retail relevance", material: true, evidenceIds: ["buff-retail"] },
    { id: "content", claim: "Active content and shelf education need", material: true, evidenceIds: ["buff-content"] },
    { id: "trigger", claim: "Current trigger", material: true, evidenceIds: ["buff-trigger"] },
  ],
  scores: {
    physicalRetailRelevance: 16,
    currentTimelyTrigger: 12,
    creatorContentActivity: 12,
    shelfEducationNeed: 13,
    currentGoshshaFit: 11,
    commercialRepeatablePotential: 8,
    practicalActionability: 4,
    evidenceQualityCompleteness: 5,
  },
  claimedGrossScore: 81,
  claimedFinalScore: 81,
  claimedBand: "Immediate Priority",
  selectionStatus: "qualified",
  benchmarkFixture: true,
};

export const elfBenchmarkCandidate: GrowthCandidateInput = {
  ...buffBenchmarkCandidate,
  id: "elf-benchmark",
  brand: "e.l.f. Cosmetics",
  productOrEvent: "Synthetic benchmark product",
  executiveSummary: "Synthetic e.l.f. fixture used only for validation coverage, not a current factual opportunity.",
  evidence: [benchmarkEvidence("elf-structural", "Synthetic structural benchmark evidence.")],
  claims: [{ id: "structural", claim: "Synthetic structural fit", material: true, evidenceIds: ["elf-structural"] }],
  scores: {
    physicalRetailRelevance: 18,
    currentTimelyTrigger: 0,
    creatorContentActivity: 15,
    shelfEducationNeed: 15,
    currentGoshshaFit: 12,
    commercialRepeatablePotential: 10,
    practicalActionability: 5,
    evidenceQualityCompleteness: 10,
  },
  opportunityType: "Exceptional Structural",
  trigger: "No current trigger is asserted in this synthetic fixture.",
  caps: ["noCurrentTrigger"],
  claimedGrossScore: 85,
  claimedFinalScore: 64,
  claimedBand: "Watch",
  selectionStatus: "watch",
};

export const unqualifiedBenchmarkCandidate: GrowthCandidateInput = {
  ...buffBenchmarkCandidate,
  id: "unqualified-benchmark",
  brand: "Synthetic Unqualified Brand",
  productOrEvent: "Unsupported product concept",
  executiveSummary: "Synthetic fixture proving unsupported opportunities remain low priority.",
  evidence: [benchmarkEvidence("unqualified-source", "Only a generic product concept is supplied.")],
  claims: [{ id: "generic", claim: "Generic product concept", material: true, evidenceIds: ["unqualified-source"] }],
  scores: {
    physicalRetailRelevance: 4,
    currentTimelyTrigger: 3,
    creatorContentActivity: 4,
    shelfEducationNeed: 5,
    currentGoshshaFit: 4,
    commercialRepeatablePotential: 3,
    practicalActionability: 2,
    evidenceQualityCompleteness: 3,
  },
  caps: ["unsupportedCentralClaim"],
  claimedGrossScore: 28,
  claimedFinalScore: 28,
  claimedBand: "Low Priority",
  selectionStatus: "rejected",
};

export const retailerDependentBenchmarkCandidate: GrowthCandidateInput = {
  ...buffBenchmarkCandidate,
  id: "retailer-dependent-benchmark",
  brand: "Synthetic Retailer-Dependent Brand",
  retailerAssessment: {
    posture: "evidence_supported_dependency",
    dependencyDescription: "The proposed synthetic workflow explicitly requires a retailer-controlled API.",
    evidenceIds: ["retailer-api-dependency"],
  },
  evidence: [benchmarkEvidence("retailer-api-dependency", "The synthetic workflow explicitly requires a retailer-controlled API.")],
  claims: [{ id: "dependency", claim: "Retailer API dependency", material: true, evidenceIds: ["retailer-api-dependency"] }],
  claimedGrossScore: 81,
  claimedFinalScore: 81,
  claimedBand: "Immediate Priority",
};

export const buffBenchmarkRun: GrowthRunRequest = {
  asOfDate: "2026-09-14",
  marketFocus: ["beauty"],
  maximumQualified: 5,
  marketPattern: "Synthetic regression fixture; not live research.",
  candidates: [buffBenchmarkCandidate],
};
